# Generated by cloudcoil-model-codegen v0.7.1
# DO NOT EDIT

from typing import Annotated, Callable, ClassVar, Literal, overload

from cloudcoil.apimachinery import (
    Condition,
    ObjectMeta,
    Quantity,
    Time,
)
from cloudcoil.pydantic import (
    UNSET,
    BaseModel,
    BaseModelBuilder,
    BuilderContextBase,
    GenericListBuilder,
    ListBuilderContext,
    Never,
    Self,
)
from cloudcoil.resources import Resource, ResourceList
from pydantic import Field


class DeviceTaint(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["DeviceTaint"]:
            return DeviceTaint

        def build(self) -> "DeviceTaint":
            return DeviceTaint(**self._attrs)

        def effect(self, value: str, /) -> Self:
            "The effect of the taint on claims that do not tolerate the taint and through such claims on the pods using them.\n\nValid effects are None, NoSchedule and NoExecute. PreferNoSchedule as used for nodes is not valid here. More effects may get added in the future. Consumers must treat unknown effects like None."
            return self._set("effect", value)

        def key(self, value: str, /) -> Self:
            "The taint key to be applied to a device. Must be a label name."
            return self._set("key", value)

        @overload
        def time_added(self, value_or_callback: Time | None, /) -> "DeviceTaint.Builder": ...

        @overload
        def time_added(
            self, value_or_callback: Callable[[Time.Builder], Time.Builder | Time], /
        ) -> "DeviceTaint.Builder": ...

        @overload
        def time_added(self, value_or_callback: Never = ...) -> "Time.BuilderContext": ...

        def time_added(self, value_or_callback=UNSET, /):
            "TimeAdded represents the time at which the taint was added or (only in a DeviceTaintRule) the effect was modified. Added automatically during create or update if not set.\n\nIn addition, in a DeviceTaintRule a value provided during an update gets replaced with the current time if the provided value is the same as the old one and the new effect is different. Changing the key and/or value while keeping the effect unchanged is possible and does not update the time stamp because the eviction which uses it is either already started (NoExecute) or not started yet (NoEffect, NoSchedule)."
            if self._in_context and value_or_callback is UNSET:
                context = Time.BuilderContext()
                context._parent_builder = self
                context._field_name = "time_added"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(Time.builder())
                if isinstance(output, Time.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("time_added", value)

        def value(self, value: str | None, /) -> Self:
            "The taint value corresponding to the taint key. Must be a label value."
            return self._set("value", value)

    class BuilderContext(BuilderContextBase["DeviceTaint.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = DeviceTaint.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for DeviceTaint."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["DeviceTaint", Builder]:
        return GenericListBuilder[DeviceTaint, DeviceTaint.Builder]()

    effect: str
    "The effect of the taint on claims that do not tolerate the taint and through such claims on the pods using them.\n\nValid effects are None, NoSchedule and NoExecute. PreferNoSchedule as used for nodes is not valid here. More effects may get added in the future. Consumers must treat unknown effects like None."
    key: str
    "The taint key to be applied to a device. Must be a label name."
    time_added: Annotated[Time | None, Field(alias="timeAdded")] = None
    "TimeAdded represents the time at which the taint was added or (only in a DeviceTaintRule) the effect was modified. Added automatically during create or update if not set.\n\nIn addition, in a DeviceTaintRule a value provided during an update gets replaced with the current time if the provided value is the same as the old one and the new effect is different. Changing the key and/or value while keeping the effect unchanged is possible and does not update the time stamp because the eviction which uses it is either already started (NoExecute) or not started yet (NoEffect, NoSchedule)."
    value: str | None = None
    "The taint value corresponding to the taint key. Must be a label value."


class DeviceTaintRuleStatus(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["DeviceTaintRuleStatus"]:
            return DeviceTaintRuleStatus

        def build(self) -> "DeviceTaintRuleStatus":
            return DeviceTaintRuleStatus(**self._attrs)

        @overload
        def conditions(
            self, value_or_callback: list[Condition] | None, /
        ) -> "DeviceTaintRuleStatus.Builder": ...

        @overload
        def conditions(
            self,
            value_or_callback: Callable[
                [GenericListBuilder[Condition, Condition.Builder]],
                GenericListBuilder[Condition, Condition.Builder] | list[Condition],
            ],
            /,
        ) -> "DeviceTaintRuleStatus.Builder": ...

        @overload
        def conditions(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[Condition.Builder]: ...

        def conditions(self, value_or_callback=UNSET, /):
            "Conditions provide information about the state of the DeviceTaintRule and the cluster at some point in time, in a machine-readable and human-readable format.\n\nThe following condition is currently defined as part of this API, more may get added: - Type: EvictionInProgress - Status: True if there are currently pods which need to be evicted, False otherwise\n  (includes the effects which don\u0027t cause eviction).\n- Reason: not specified, may change - Message: includes information about number of pending pods and already evicted pods\n  in a human-readable format, updated periodically, may change\n\nFor `effect: None`, the condition above gets set once for each change to the spec, with the message containing information about what would happen if the effect was `NoExecute`. This feedback can be used to decide whether changing the effect to `NoExecute` will work as intended. It only gets set once to avoid having to constantly update the status.\n\nMust have 8 or fewer entries."
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[Condition.Builder]()
                context._parent_builder = self
                context._field_name = "conditions"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(Condition.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("conditions", value)

    class BuilderContext(BuilderContextBase["DeviceTaintRuleStatus.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = DeviceTaintRuleStatus.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for DeviceTaintRuleStatus."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["DeviceTaintRuleStatus", Builder]:
        return GenericListBuilder[DeviceTaintRuleStatus, DeviceTaintRuleStatus.Builder]()

    conditions: list[Condition] | None = None
    "Conditions provide information about the state of the DeviceTaintRule and the cluster at some point in time, in a machine-readable and human-readable format.\n\nThe following condition is currently defined as part of this API, more may get added: - Type: EvictionInProgress - Status: True if there are currently pods which need to be evicted, False otherwise\n  (includes the effects which don\u0027t cause eviction).\n- Reason: not specified, may change - Message: includes information about number of pending pods and already evicted pods\n  in a human-readable format, updated periodically, may change\n\nFor `effect: None`, the condition above gets set once for each change to the spec, with the message containing information about what would happen if the effect was `NoExecute`. This feedback can be used to decide whether changing the effect to `NoExecute` will work as intended. It only gets set once to avoid having to constantly update the status.\n\nMust have 8 or fewer entries."


class DeviceTaintSelector(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["DeviceTaintSelector"]:
            return DeviceTaintSelector

        def build(self) -> "DeviceTaintSelector":
            return DeviceTaintSelector(**self._attrs)

        def device(self, value: str | None, /) -> Self:
            "If device is set, only devices with that name are selected. This field corresponds to slice.spec.devices[].name.\n\nSetting also driver and pool may be required to avoid ambiguity, but is not required."
            return self._set("device", value)

        def driver(self, value: str | None, /) -> Self:
            "If driver is set, only devices from that driver are selected. This fields corresponds to slice.spec.driver."
            return self._set("driver", value)

        def pool(self, value: str | None, /) -> Self:
            "If pool is set, only devices in that pool are selected.\n\nAlso setting the driver name may be useful to avoid ambiguity when different drivers use the same pool name, but this is not required because selecting pools from different drivers may also be useful, for example when drivers with node-local devices use the node name as their pool name."
            return self._set("pool", value)

    class BuilderContext(BuilderContextBase["DeviceTaintSelector.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = DeviceTaintSelector.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for DeviceTaintSelector."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["DeviceTaintSelector", Builder]:
        return GenericListBuilder[DeviceTaintSelector, DeviceTaintSelector.Builder]()

    device: str | None = None
    "If device is set, only devices with that name are selected. This field corresponds to slice.spec.devices[].name.\n\nSetting also driver and pool may be required to avoid ambiguity, but is not required."
    driver: str | None = None
    "If driver is set, only devices from that driver are selected. This fields corresponds to slice.spec.driver."
    pool: str | None = None
    "If pool is set, only devices in that pool are selected.\n\nAlso setting the driver name may be useful to avoid ambiguity when different drivers use the same pool name, but this is not required because selecting pools from different drivers may also be useful, for example when drivers with node-local devices use the node name as their pool name."


class PartitionTypeStatus(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["PartitionTypeStatus"]:
            return PartitionTypeStatus

        def build(self) -> "PartitionTypeStatus":
            return PartitionTypeStatus(**self._attrs)

        def allocatable(self, value: int, /) -> Self:
            "Allocatable is the number of additional devices of this partition type that could still be allocated given current shared-counter consumption."
            return self._set("allocatable", value)

        def attribute(self, value: str, /) -> Self:
            "Attribute is the fully qualified name of the device attribute whose value groups this entry. It is the PartitionTypeAttribute declared by the devices\u0027 own slice, or the default named in the request when their slice declares none."
            return self._set("attribute", value)

        def total(self, value: int, /) -> Self:
            "Total is the number of devices of this partition type in the pool."
            return self._set("total", value)

        def type(self, value: str, /) -> Self:
            'Type is the partition type value (e.g. "Full" or "Half").'
            return self._set("type", value)

    class BuilderContext(BuilderContextBase["PartitionTypeStatus.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = PartitionTypeStatus.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for PartitionTypeStatus."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["PartitionTypeStatus", Builder]:
        return GenericListBuilder[PartitionTypeStatus, PartitionTypeStatus.Builder]()

    allocatable: int
    "Allocatable is the number of additional devices of this partition type that could still be allocated given current shared-counter consumption."
    attribute: str
    "Attribute is the fully qualified name of the device attribute whose value groups this entry. It is the PartitionTypeAttribute declared by the devices\u0027 own slice, or the default named in the request when their slice declares none."
    total: int
    "Total is the number of devices of this partition type in the pool."
    type: str
    'Type is the partition type value (e.g. "Full" or "Half").'


class ResourcePoolStatusRequestSpec(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["ResourcePoolStatusRequestSpec"]:
            return ResourcePoolStatusRequestSpec

        def build(self) -> "ResourcePoolStatusRequestSpec":
            return ResourcePoolStatusRequestSpec(**self._attrs)

        def default_partition_type_attribute(self, value: str | None, /) -> Self:
            'DefaultPartitionTypeAttribute optionally names a device attribute (by its fully qualified name, e.g. "gpu.example.com/profile") to use as the default grouping attribute for partitionable devices whose slice has not declared one themselves.\n\nA slice\u0027s own PartitionTypeAttribute always takes precedence. This default applies only to devices whose slice does not declare one, so that a request can still get an accurate partitionSummary from a driver that has not been updated to declare it. When neither the slice nor this default names an attribute, a partitionable pool reports no partitionSummary.\n\nMust include the domain qualifier.'
            return self._set("default_partition_type_attribute", value)

        def driver(self, value: str, /) -> Self:
            'Driver specifies the DRA driver name to filter pools. Only pools from ResourceSlices with this driver will be included. Must be a DNS subdomain (e.g., "gpu.example.com").'
            return self._set("driver", value)

        def limit(self, value: int | None, /) -> Self:
            "Limit optionally specifies the maximum number of pools to return in the status. If more pools match the filter criteria, the response will be truncated (i.e., len(status.pools) \u003c status.poolCount).\n\nDefault: 100 Minimum: 1 Maximum: 1000"
            return self._set("limit", value)

        def pool_name(self, value: str | None, /) -> Self:
            'PoolName optionally filters to a specific pool name. If not specified, all pools from the specified driver are included. When specified, must be a non-empty valid resource pool name (DNS subdomains separated by "/").'
            return self._set("pool_name", value)

    class BuilderContext(BuilderContextBase["ResourcePoolStatusRequestSpec.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = ResourcePoolStatusRequestSpec.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ResourcePoolStatusRequestSpec."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["ResourcePoolStatusRequestSpec", Builder]:
        return GenericListBuilder[
            ResourcePoolStatusRequestSpec, ResourcePoolStatusRequestSpec.Builder
        ]()

    default_partition_type_attribute: Annotated[
        str | None, Field(alias="defaultPartitionTypeAttribute")
    ] = None
    'DefaultPartitionTypeAttribute optionally names a device attribute (by its fully qualified name, e.g. "gpu.example.com/profile") to use as the default grouping attribute for partitionable devices whose slice has not declared one themselves.\n\nA slice\u0027s own PartitionTypeAttribute always takes precedence. This default applies only to devices whose slice does not declare one, so that a request can still get an accurate partitionSummary from a driver that has not been updated to declare it. When neither the slice nor this default names an attribute, a partitionable pool reports no partitionSummary.\n\nMust include the domain qualifier.'
    driver: str
    'Driver specifies the DRA driver name to filter pools. Only pools from ResourceSlices with this driver will be included. Must be a DNS subdomain (e.g., "gpu.example.com").'
    limit: int | None = None
    "Limit optionally specifies the maximum number of pools to return in the status. If more pools match the filter criteria, the response will be truncated (i.e., len(status.pools) \u003c status.poolCount).\n\nDefault: 100 Minimum: 1 Maximum: 1000"
    pool_name: Annotated[str | None, Field(alias="poolName")] = None
    'PoolName optionally filters to a specific pool name. If not specified, all pools from the specified driver are included. When specified, must be a non-empty valid resource pool name (DNS subdomains separated by "/").'


class ShareableCapacityStatus(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["ShareableCapacityStatus"]:
            return ShareableCapacityStatus

        def build(self) -> "ShareableCapacityStatus":
            return ShareableCapacityStatus(**self._attrs)

        @overload
        def available(
            self, value_or_callback: Quantity, /
        ) -> "ShareableCapacityStatus.Builder": ...

        @overload
        def available(
            self,
            value_or_callback: Callable[[Quantity.Builder], Quantity.Builder | Quantity],
            /,
        ) -> "ShareableCapacityStatus.Builder": ...

        @overload
        def available(self, value_or_callback: Never = ...) -> "Quantity.BuilderContext": ...

        def available(self, value_or_callback=UNSET, /):
            "Available is Total minus Consumed, never negative."
            if self._in_context and value_or_callback is UNSET:
                context = Quantity.BuilderContext()
                context._parent_builder = self
                context._field_name = "available"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(Quantity.builder())
                if isinstance(output, Quantity.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("available", value)

        @overload
        def consumed(self, value_or_callback: Quantity, /) -> "ShareableCapacityStatus.Builder": ...

        @overload
        def consumed(
            self,
            value_or_callback: Callable[[Quantity.Builder], Quantity.Builder | Quantity],
            /,
        ) -> "ShareableCapacityStatus.Builder": ...

        @overload
        def consumed(self, value_or_callback: Never = ...) -> "Quantity.BuilderContext": ...

        def consumed(self, value_or_callback=UNSET, /):
            "Consumed is the amount drawn by current allocations."
            if self._in_context and value_or_callback is UNSET:
                context = Quantity.BuilderContext()
                context._parent_builder = self
                context._field_name = "consumed"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(Quantity.builder())
                if isinstance(output, Quantity.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("consumed", value)

        def name(self, value: str, /) -> Self:
            "Name is the capacity name."
            return self._set("name", value)

        @overload
        def total(self, value_or_callback: Quantity, /) -> "ShareableCapacityStatus.Builder": ...

        @overload
        def total(
            self,
            value_or_callback: Callable[[Quantity.Builder], Quantity.Builder | Quantity],
            /,
        ) -> "ShareableCapacityStatus.Builder": ...

        @overload
        def total(self, value_or_callback: Never = ...) -> "Quantity.BuilderContext": ...

        def total(self, value_or_callback=UNSET, /):
            "Total is the sum of this capacity across shareable devices in the pool."
            if self._in_context and value_or_callback is UNSET:
                context = Quantity.BuilderContext()
                context._parent_builder = self
                context._field_name = "total"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(Quantity.builder())
                if isinstance(output, Quantity.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("total", value)

    class BuilderContext(BuilderContextBase["ShareableCapacityStatus.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = ShareableCapacityStatus.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ShareableCapacityStatus."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["ShareableCapacityStatus", Builder]:
        return GenericListBuilder[ShareableCapacityStatus, ShareableCapacityStatus.Builder]()

    available: Quantity
    "Available is Total minus Consumed, never negative."
    consumed: Quantity
    "Consumed is the amount drawn by current allocations."
    name: str
    "Name is the capacity name."
    total: Quantity
    "Total is the sum of this capacity across shareable devices in the pool."


class ShareableSummaryStatus(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["ShareableSummaryStatus"]:
            return ShareableSummaryStatus

        def build(self) -> "ShareableSummaryStatus":
            return ShareableSummaryStatus(**self._attrs)

        @overload
        def capacity(
            self, value_or_callback: list[ShareableCapacityStatus] | None, /
        ) -> "ShareableSummaryStatus.Builder": ...

        @overload
        def capacity(
            self,
            value_or_callback: Callable[
                [GenericListBuilder[ShareableCapacityStatus, ShareableCapacityStatus.Builder]],
                GenericListBuilder[ShareableCapacityStatus, ShareableCapacityStatus.Builder]
                | list[ShareableCapacityStatus],
            ],
            /,
        ) -> "ShareableSummaryStatus.Builder": ...

        @overload
        def capacity(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[ShareableCapacityStatus.Builder]: ...

        def capacity(self, value_or_callback=UNSET, /):
            "Capacity reports aggregate total, consumed, and available amounts per shareable capacity key across the pool."
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[ShareableCapacityStatus.Builder]()
                context._parent_builder = self
                context._field_name = "capacity"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ShareableCapacityStatus.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("capacity", value)

        def fully_available_devices(self, value: int, /) -> Self:
            "FullyAvailableDevices is the number of shareable devices with no capacity consumed."
            return self._set("fully_available_devices", value)

        def partially_available_devices(self, value: int, /) -> Self:
            "PartiallyAvailableDevices is the number of shareable devices with some but not all capacity consumed."
            return self._set("partially_available_devices", value)

    class BuilderContext(BuilderContextBase["ShareableSummaryStatus.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = ShareableSummaryStatus.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ShareableSummaryStatus."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["ShareableSummaryStatus", Builder]:
        return GenericListBuilder[ShareableSummaryStatus, ShareableSummaryStatus.Builder]()

    capacity: list[ShareableCapacityStatus] | None = None
    "Capacity reports aggregate total, consumed, and available amounts per shareable capacity key across the pool."
    fully_available_devices: Annotated[int, Field(alias="fullyAvailableDevices")]
    "FullyAvailableDevices is the number of shareable devices with no capacity consumed."
    partially_available_devices: Annotated[int, Field(alias="partiallyAvailableDevices")]
    "PartiallyAvailableDevices is the number of shareable devices with some but not all capacity consumed."


class DeviceTaintRuleSpec(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["DeviceTaintRuleSpec"]:
            return DeviceTaintRuleSpec

        def build(self) -> "DeviceTaintRuleSpec":
            return DeviceTaintRuleSpec(**self._attrs)

        @overload
        def device_selector(
            self, value_or_callback: DeviceTaintSelector | None, /
        ) -> "DeviceTaintRuleSpec.Builder": ...

        @overload
        def device_selector(
            self,
            value_or_callback: Callable[
                [DeviceTaintSelector.Builder],
                DeviceTaintSelector.Builder | DeviceTaintSelector,
            ],
            /,
        ) -> "DeviceTaintRuleSpec.Builder": ...

        @overload
        def device_selector(
            self, value_or_callback: Never = ...
        ) -> "DeviceTaintSelector.BuilderContext": ...

        def device_selector(self, value_or_callback=UNSET, /):
            "DeviceSelector defines which device(s) the taint is applied to. All selector criteria must be satisfied for a device to match. The empty selector matches all devices. Without a selector, no devices are matches."
            if self._in_context and value_or_callback is UNSET:
                context = DeviceTaintSelector.BuilderContext()
                context._parent_builder = self
                context._field_name = "device_selector"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(DeviceTaintSelector.builder())
                if isinstance(output, DeviceTaintSelector.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("device_selector", value)

        @overload
        def taint(self, value_or_callback: DeviceTaint, /) -> "DeviceTaintRuleSpec.Builder": ...

        @overload
        def taint(
            self,
            value_or_callback: Callable[[DeviceTaint.Builder], DeviceTaint.Builder | DeviceTaint],
            /,
        ) -> "DeviceTaintRuleSpec.Builder": ...

        @overload
        def taint(self, value_or_callback: Never = ...) -> "DeviceTaint.BuilderContext": ...

        def taint(self, value_or_callback=UNSET, /):
            "The taint that gets applied to matching devices."
            if self._in_context and value_or_callback is UNSET:
                context = DeviceTaint.BuilderContext()
                context._parent_builder = self
                context._field_name = "taint"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(DeviceTaint.builder())
                if isinstance(output, DeviceTaint.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("taint", value)

    class BuilderContext(BuilderContextBase["DeviceTaintRuleSpec.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = DeviceTaintRuleSpec.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for DeviceTaintRuleSpec."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["DeviceTaintRuleSpec", Builder]:
        return GenericListBuilder[DeviceTaintRuleSpec, DeviceTaintRuleSpec.Builder]()

    device_selector: Annotated[DeviceTaintSelector | None, Field(alias="deviceSelector")] = None
    "DeviceSelector defines which device(s) the taint is applied to. All selector criteria must be satisfied for a device to match. The empty selector matches all devices. Without a selector, no devices are matches."
    taint: DeviceTaint
    "The taint that gets applied to matching devices."


class PoolStatus(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["PoolStatus"]:
            return PoolStatus

        def build(self) -> "PoolStatus":
            return PoolStatus(**self._attrs)

        def allocated_devices(self, value: int | None, /) -> Self:
            "AllocatedDevices is the number of devices currently allocated to claims. A value of 0 means no devices are allocated. May be unset when validationError is set."
            return self._set("allocated_devices", value)

        def available_devices(self, value: int | None, /) -> Self:
            "AvailableDevices is the number of devices available for allocation. This equals TotalDevices - AllocatedDevices - UnavailableDevices. A value of 0 means no devices are currently available. May be unset when validationError is set."
            return self._set("available_devices", value)

        def driver(self, value: str, /) -> Self:
            'Driver is the DRA driver name for this pool. Must be a DNS subdomain (e.g., "gpu.example.com").'
            return self._set("driver", value)

        def generation(self, value: int, /) -> Self:
            "Generation is the pool generation observed across all ResourceSlices in this pool. Only the latest generation is reported. During a generation rollout, if not all slices at the latest generation have been published, the pool is included with a validationError and device counts unset."
            return self._set("generation", value)

        def node_name(self, value: str | None, /) -> Self:
            "NodeName is the node this pool is associated with. When omitted, the pool is not associated with a specific node. Must be a valid DNS subdomain name (RFC1123)."
            return self._set("node_name", value)

        @overload
        def partition_summary(
            self, value_or_callback: list[PartitionTypeStatus] | None, /
        ) -> "PoolStatus.Builder": ...

        @overload
        def partition_summary(
            self,
            value_or_callback: Callable[
                [GenericListBuilder[PartitionTypeStatus, PartitionTypeStatus.Builder]],
                GenericListBuilder[PartitionTypeStatus, PartitionTypeStatus.Builder]
                | list[PartitionTypeStatus],
            ],
            /,
        ) -> "PoolStatus.Builder": ...

        @overload
        def partition_summary(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[PartitionTypeStatus.Builder]: ...

        def partition_summary(self, value_or_callback=UNSET, /):
            "PartitionSummary reports allocatability per (attribute, partition type) for a partitionable pool that publishes SharedCounters. Each entry names the grouping attribute it was resolved from: the PartitionTypeAttribute declared by a device\u0027s own slice, or for devices whose slice declares none, the default named in the request. A pool that mixes partitions declared under different attributes reports each independently. When no slice declares an attribute and the request names no default, the pool reports no partition summary."
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[PartitionTypeStatus.Builder]()
                context._parent_builder = self
                context._field_name = "partition_summary"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(PartitionTypeStatus.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("partition_summary", value)

        def pool_name(self, value: str, /) -> Self:
            'PoolName is the name of the pool. Must be a valid resource pool name (DNS subdomains separated by "/").'
            return self._set("pool_name", value)

        def resource_slice_count(self, value: int | None, /) -> Self:
            "ResourceSliceCount is the number of ResourceSlices that make up this pool. May be unset when validationError is set."
            return self._set("resource_slice_count", value)

        @overload
        def shareable_summary(
            self, value_or_callback: ShareableSummaryStatus | None, /
        ) -> "PoolStatus.Builder": ...

        @overload
        def shareable_summary(
            self,
            value_or_callback: Callable[
                [ShareableSummaryStatus.Builder],
                ShareableSummaryStatus.Builder | ShareableSummaryStatus,
            ],
            /,
        ) -> "PoolStatus.Builder": ...

        @overload
        def shareable_summary(
            self, value_or_callback: Never = ...
        ) -> "ShareableSummaryStatus.BuilderContext": ...

        def shareable_summary(self, value_or_callback=UNSET, /):
            "ShareableSummary reports aggregate capacity for a pool that contains devices with AllowMultipleAllocations. It is populated only when at least one device in the pool is shareable."
            if self._in_context and value_or_callback is UNSET:
                context = ShareableSummaryStatus.BuilderContext()
                context._parent_builder = self
                context._field_name = "shareable_summary"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ShareableSummaryStatus.builder())
                if isinstance(output, ShareableSummaryStatus.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("shareable_summary", value)

        def total_devices(self, value: int | None, /) -> Self:
            "TotalDevices is the total number of devices in the pool across all slices. A value of 0 means the pool has no devices. May be unset when validationError is set."
            return self._set("total_devices", value)

        def unavailable_devices(self, value: int | None, /) -> Self:
            "UnavailableDevices is the number of devices that are not available due to taints or other conditions, but are not allocated. A value of 0 means all unallocated devices are available. May be unset when validationError is set."
            return self._set("unavailable_devices", value)

        def validation_error(self, value: str | None, /) -> Self:
            "ValidationError is set when the pool\u0027s data could not be fully validated (e.g., incomplete slice publication). When set, device count fields and ResourceSliceCount may be unset."
            return self._set("validation_error", value)

    class BuilderContext(BuilderContextBase["PoolStatus.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = PoolStatus.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for PoolStatus."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["PoolStatus", Builder]:
        return GenericListBuilder[PoolStatus, PoolStatus.Builder]()

    allocated_devices: Annotated[int | None, Field(alias="allocatedDevices")] = None
    "AllocatedDevices is the number of devices currently allocated to claims. A value of 0 means no devices are allocated. May be unset when validationError is set."
    available_devices: Annotated[int | None, Field(alias="availableDevices")] = None
    "AvailableDevices is the number of devices available for allocation. This equals TotalDevices - AllocatedDevices - UnavailableDevices. A value of 0 means no devices are currently available. May be unset when validationError is set."
    driver: str
    'Driver is the DRA driver name for this pool. Must be a DNS subdomain (e.g., "gpu.example.com").'
    generation: int
    "Generation is the pool generation observed across all ResourceSlices in this pool. Only the latest generation is reported. During a generation rollout, if not all slices at the latest generation have been published, the pool is included with a validationError and device counts unset."
    node_name: Annotated[str | None, Field(alias="nodeName")] = None
    "NodeName is the node this pool is associated with. When omitted, the pool is not associated with a specific node. Must be a valid DNS subdomain name (RFC1123)."
    partition_summary: Annotated[
        list[PartitionTypeStatus] | None, Field(alias="partitionSummary")
    ] = None
    "PartitionSummary reports allocatability per (attribute, partition type) for a partitionable pool that publishes SharedCounters. Each entry names the grouping attribute it was resolved from: the PartitionTypeAttribute declared by a device\u0027s own slice, or for devices whose slice declares none, the default named in the request. A pool that mixes partitions declared under different attributes reports each independently. When no slice declares an attribute and the request names no default, the pool reports no partition summary."
    pool_name: Annotated[str, Field(alias="poolName")]
    'PoolName is the name of the pool. Must be a valid resource pool name (DNS subdomains separated by "/").'
    resource_slice_count: Annotated[int | None, Field(alias="resourceSliceCount")] = None
    "ResourceSliceCount is the number of ResourceSlices that make up this pool. May be unset when validationError is set."
    shareable_summary: Annotated[ShareableSummaryStatus | None, Field(alias="shareableSummary")] = (
        None
    )
    "ShareableSummary reports aggregate capacity for a pool that contains devices with AllowMultipleAllocations. It is populated only when at least one device in the pool is shareable."
    total_devices: Annotated[int | None, Field(alias="totalDevices")] = None
    "TotalDevices is the total number of devices in the pool across all slices. A value of 0 means the pool has no devices. May be unset when validationError is set."
    unavailable_devices: Annotated[int | None, Field(alias="unavailableDevices")] = None
    "UnavailableDevices is the number of devices that are not available due to taints or other conditions, but are not allocated. A value of 0 means all unallocated devices are available. May be unset when validationError is set."
    validation_error: Annotated[str | None, Field(alias="validationError")] = None
    "ValidationError is set when the pool\u0027s data could not be fully validated (e.g., incomplete slice publication). When set, device count fields and ResourceSliceCount may be unset."


class ResourcePoolStatusRequestStatus(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["ResourcePoolStatusRequestStatus"]:
            return ResourcePoolStatusRequestStatus

        def build(self) -> "ResourcePoolStatusRequestStatus":
            return ResourcePoolStatusRequestStatus(**self._attrs)

        @overload
        def conditions(
            self, value_or_callback: list[Condition] | None, /
        ) -> "ResourcePoolStatusRequestStatus.Builder": ...

        @overload
        def conditions(
            self,
            value_or_callback: Callable[
                [GenericListBuilder[Condition, Condition.Builder]],
                GenericListBuilder[Condition, Condition.Builder] | list[Condition],
            ],
            /,
        ) -> "ResourcePoolStatusRequestStatus.Builder": ...

        @overload
        def conditions(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[Condition.Builder]: ...

        def conditions(self, value_or_callback=UNSET, /):
            'Conditions provide information about the state of the request. A condition with type=Complete or type=Failed will always be set when the status is populated.\n\nKnown condition types: - "Complete": True when the request has been processed successfully - "Failed": True when the request could not be processed'
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[Condition.Builder]()
                context._parent_builder = self
                context._field_name = "conditions"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(Condition.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("conditions", value)

        def pool_count(self, value: int, /) -> Self:
            "PoolCount is the total number of pools that matched the filter criteria, regardless of truncation. This helps users understand how many pools exist even when the response is truncated. A value of 0 means no pools matched the filter criteria."
            return self._set("pool_count", value)

        @overload
        def pools(
            self, value_or_callback: list[PoolStatus] | None, /
        ) -> "ResourcePoolStatusRequestStatus.Builder": ...

        @overload
        def pools(
            self,
            value_or_callback: Callable[
                [GenericListBuilder[PoolStatus, PoolStatus.Builder]],
                GenericListBuilder[PoolStatus, PoolStatus.Builder] | list[PoolStatus],
            ],
            /,
        ) -> "ResourcePoolStatusRequestStatus.Builder": ...

        @overload
        def pools(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[PoolStatus.Builder]: ...

        def pools(self, value_or_callback=UNSET, /):
            "Pools contains the first `spec.limit` matching pools, sorted by driver then pool name. If `len(pools) \u003c poolCount`, the list was truncated. When omitted, no pools matched the request filters."
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[PoolStatus.Builder]()
                context._parent_builder = self
                context._field_name = "pools"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(PoolStatus.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("pools", value)

    class BuilderContext(BuilderContextBase["ResourcePoolStatusRequestStatus.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = ResourcePoolStatusRequestStatus.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ResourcePoolStatusRequestStatus."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["ResourcePoolStatusRequestStatus", Builder]:
        return GenericListBuilder[
            ResourcePoolStatusRequestStatus, ResourcePoolStatusRequestStatus.Builder
        ]()

    conditions: list[Condition] | None = None
    'Conditions provide information about the state of the request. A condition with type=Complete or type=Failed will always be set when the status is populated.\n\nKnown condition types: - "Complete": True when the request has been processed successfully - "Failed": True when the request could not be processed'
    pool_count: Annotated[int, Field(alias="poolCount")]
    "PoolCount is the total number of pools that matched the filter criteria, regardless of truncation. This helps users understand how many pools exist even when the response is truncated. A value of 0 means no pools matched the filter criteria."
    pools: list[PoolStatus] | None = None
    "Pools contains the first `spec.limit` matching pools, sorted by driver then pool name. If `len(pools) \u003c poolCount`, the list was truncated. When omitted, no pools matched the request filters."


class DeviceTaintRule(Resource):
    __cloudcoil_api__: ClassVar[dict] = {
        "plural": "devicetaintrules",
        "scope": "Cluster",
        "status": False,
    }

    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["DeviceTaintRule"]:
            return DeviceTaintRule

        def build(self) -> "DeviceTaintRule":
            return DeviceTaintRule(**self._attrs)

        def api_version(self, value: Literal["resource.k8s.io/v1alpha3"], /) -> Self:
            "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
            return self._set("api_version", value)

        def kind(self, value: Literal["DeviceTaintRule"], /) -> Self:
            "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
            return self._set("kind", value)

        @overload
        def metadata(
            self, value_or_callback: ObjectMeta | None, /
        ) -> "DeviceTaintRule.Builder": ...

        @overload
        def metadata(
            self,
            value_or_callback: Callable[[ObjectMeta.Builder], ObjectMeta.Builder | ObjectMeta],
            /,
        ) -> "DeviceTaintRule.Builder": ...

        @overload
        def metadata(self, value_or_callback: Never = ...) -> "ObjectMeta.BuilderContext": ...

        def metadata(self, value_or_callback=UNSET, /):
            "Standard object metadata"
            if self._in_context and value_or_callback is UNSET:
                context = ObjectMeta.BuilderContext()
                context._parent_builder = self
                context._field_name = "metadata"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ObjectMeta.builder())
                if isinstance(output, ObjectMeta.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("metadata", value)

        @overload
        def spec(self, value_or_callback: DeviceTaintRuleSpec, /) -> "DeviceTaintRule.Builder": ...

        @overload
        def spec(
            self,
            value_or_callback: Callable[
                [DeviceTaintRuleSpec.Builder],
                DeviceTaintRuleSpec.Builder | DeviceTaintRuleSpec,
            ],
            /,
        ) -> "DeviceTaintRule.Builder": ...

        @overload
        def spec(self, value_or_callback: Never = ...) -> "DeviceTaintRuleSpec.BuilderContext": ...

        def spec(self, value_or_callback=UNSET, /):
            "Spec specifies the selector and one taint.\n\nChanging the spec automatically increments the metadata.generation number."
            if self._in_context and value_or_callback is UNSET:
                context = DeviceTaintRuleSpec.BuilderContext()
                context._parent_builder = self
                context._field_name = "spec"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(DeviceTaintRuleSpec.builder())
                if isinstance(output, DeviceTaintRuleSpec.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("spec", value)

        @overload
        def status(
            self, value_or_callback: DeviceTaintRuleStatus | None, /
        ) -> "DeviceTaintRule.Builder": ...

        @overload
        def status(
            self,
            value_or_callback: Callable[
                [DeviceTaintRuleStatus.Builder],
                DeviceTaintRuleStatus.Builder | DeviceTaintRuleStatus,
            ],
            /,
        ) -> "DeviceTaintRule.Builder": ...

        @overload
        def status(
            self, value_or_callback: Never = ...
        ) -> "DeviceTaintRuleStatus.BuilderContext": ...

        def status(self, value_or_callback=UNSET, /):
            "Status provides information about what was requested in the spec."
            if self._in_context and value_or_callback is UNSET:
                context = DeviceTaintRuleStatus.BuilderContext()
                context._parent_builder = self
                context._field_name = "status"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(DeviceTaintRuleStatus.builder())
                if isinstance(output, DeviceTaintRuleStatus.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("status", value)

    class BuilderContext(BuilderContextBase["DeviceTaintRule.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = DeviceTaintRule.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for DeviceTaintRule."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["DeviceTaintRule", Builder]:
        return GenericListBuilder[DeviceTaintRule, DeviceTaintRule.Builder]()

    api_version: Annotated[Literal["resource.k8s.io/v1alpha3"], Field(alias="apiVersion")] = (
        "resource.k8s.io/v1alpha3"
    )
    "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
    kind: Literal["DeviceTaintRule"] = "DeviceTaintRule"
    "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
    metadata: ObjectMeta | None = None
    "Standard object metadata"
    spec: DeviceTaintRuleSpec
    "Spec specifies the selector and one taint.\n\nChanging the spec automatically increments the metadata.generation number."
    status: DeviceTaintRuleStatus | None = None
    "Status provides information about what was requested in the spec."


DeviceTaintRuleList = ResourceList[DeviceTaintRule]


class ResourcePoolStatusRequest(Resource):
    __cloudcoil_api__: ClassVar[dict] = {
        "plural": "resourcepoolstatusrequests",
        "scope": "Cluster",
        "status": False,
    }

    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["ResourcePoolStatusRequest"]:
            return ResourcePoolStatusRequest

        def build(self) -> "ResourcePoolStatusRequest":
            return ResourcePoolStatusRequest(**self._attrs)

        def api_version(self, value: Literal["resource.k8s.io/v1alpha3"], /) -> Self:
            "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
            return self._set("api_version", value)

        def kind(self, value: Literal["ResourcePoolStatusRequest"], /) -> Self:
            "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
            return self._set("kind", value)

        @overload
        def metadata(
            self, value_or_callback: ObjectMeta | None, /
        ) -> "ResourcePoolStatusRequest.Builder": ...

        @overload
        def metadata(
            self,
            value_or_callback: Callable[[ObjectMeta.Builder], ObjectMeta.Builder | ObjectMeta],
            /,
        ) -> "ResourcePoolStatusRequest.Builder": ...

        @overload
        def metadata(self, value_or_callback: Never = ...) -> "ObjectMeta.BuilderContext": ...

        def metadata(self, value_or_callback=UNSET, /):
            "Standard object metadata"
            if self._in_context and value_or_callback is UNSET:
                context = ObjectMeta.BuilderContext()
                context._parent_builder = self
                context._field_name = "metadata"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ObjectMeta.builder())
                if isinstance(output, ObjectMeta.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("metadata", value)

        @overload
        def spec(
            self, value_or_callback: ResourcePoolStatusRequestSpec, /
        ) -> "ResourcePoolStatusRequest.Builder": ...

        @overload
        def spec(
            self,
            value_or_callback: Callable[
                [ResourcePoolStatusRequestSpec.Builder],
                ResourcePoolStatusRequestSpec.Builder | ResourcePoolStatusRequestSpec,
            ],
            /,
        ) -> "ResourcePoolStatusRequest.Builder": ...

        @overload
        def spec(
            self, value_or_callback: Never = ...
        ) -> "ResourcePoolStatusRequestSpec.BuilderContext": ...

        def spec(self, value_or_callback=UNSET, /):
            "Spec defines the filters for which pools to include in the status. The spec is immutable once created."
            if self._in_context and value_or_callback is UNSET:
                context = ResourcePoolStatusRequestSpec.BuilderContext()
                context._parent_builder = self
                context._field_name = "spec"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ResourcePoolStatusRequestSpec.builder())
                if isinstance(output, ResourcePoolStatusRequestSpec.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("spec", value)

        @overload
        def status(
            self, value_or_callback: ResourcePoolStatusRequestStatus | None, /
        ) -> "ResourcePoolStatusRequest.Builder": ...

        @overload
        def status(
            self,
            value_or_callback: Callable[
                [ResourcePoolStatusRequestStatus.Builder],
                ResourcePoolStatusRequestStatus.Builder | ResourcePoolStatusRequestStatus,
            ],
            /,
        ) -> "ResourcePoolStatusRequest.Builder": ...

        @overload
        def status(
            self, value_or_callback: Never = ...
        ) -> "ResourcePoolStatusRequestStatus.BuilderContext": ...

        def status(self, value_or_callback=UNSET, /):
            "Status is populated by the controller with the calculated pool status. When status is non-nil, the request is considered complete and the entire object becomes immutable."
            if self._in_context and value_or_callback is UNSET:
                context = ResourcePoolStatusRequestStatus.BuilderContext()
                context._parent_builder = self
                context._field_name = "status"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ResourcePoolStatusRequestStatus.builder())
                if isinstance(output, ResourcePoolStatusRequestStatus.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("status", value)

    class BuilderContext(BuilderContextBase["ResourcePoolStatusRequest.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = ResourcePoolStatusRequest.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ResourcePoolStatusRequest."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["ResourcePoolStatusRequest", Builder]:
        return GenericListBuilder[ResourcePoolStatusRequest, ResourcePoolStatusRequest.Builder]()

    api_version: Annotated[Literal["resource.k8s.io/v1alpha3"], Field(alias="apiVersion")] = (
        "resource.k8s.io/v1alpha3"
    )
    "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
    kind: Literal["ResourcePoolStatusRequest"] = "ResourcePoolStatusRequest"
    "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
    metadata: ObjectMeta | None = None
    "Standard object metadata"
    spec: ResourcePoolStatusRequestSpec
    "Spec defines the filters for which pools to include in the status. The spec is immutable once created."
    status: ResourcePoolStatusRequestStatus | None = None
    "Status is populated by the controller with the calculated pool status. When status is non-nil, the request is considered complete and the entire object becomes immutable."


ResourcePoolStatusRequestList = ResourceList[ResourcePoolStatusRequest]
