# Generated by cloudcoil-model-codegen v0.7.0
# DO NOT EDIT

from typing import Annotated, Callable, Literal, overload

from cloudcoil.apimachinery import (
    ObjectMeta,
    Time,
)
from cloudcoil.pydantic import (
    UNSET,
    BaseModel,
    BaseModelBuilder,
    BuilderContextBase,
    GenericListBuilder,
    Never,
    Self,
)
from cloudcoil.resources import Resource
from pydantic import Field


class BoundObjectReference(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["BoundObjectReference"]:
            return BoundObjectReference

        def build(self) -> "BoundObjectReference":
            return BoundObjectReference(**self._attrs)

        def api_version(self, value: str | None, /) -> Self:
            "API version of the referent."
            return self._set("api_version", value)

        def kind(self, value: str | None, /) -> Self:
            "Kind of the referent. Valid kinds are \u0027Pod\u0027 and \u0027Secret\u0027."
            return self._set("kind", value)

        def name(self, value: str | None, /) -> Self:
            "Name of the referent."
            return self._set("name", value)

        def uid(self, value: str | None, /) -> Self:
            "UID of the referent."
            return self._set("uid", value)

    class BuilderContext(BuilderContextBase["BoundObjectReference.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = BoundObjectReference.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for BoundObjectReference."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["BoundObjectReference", Builder]:
        return GenericListBuilder[BoundObjectReference, BoundObjectReference.Builder]()

    api_version: Annotated[str | None, Field(alias="apiVersion")] = None
    "API version of the referent."
    kind: str | None = None
    "Kind of the referent. Valid kinds are \u0027Pod\u0027 and \u0027Secret\u0027."
    name: str | None = None
    "Name of the referent."
    uid: str | None = None
    "UID of the referent."


class TokenRequestSpec(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["TokenRequestSpec"]:
            return TokenRequestSpec

        def build(self) -> "TokenRequestSpec":
            return TokenRequestSpec(**self._attrs)

        def audiences(self, value: list[str], /) -> Self:
            "Audiences are the intendend audiences of the token. A recipient of a token must identify themself with an identifier in the list of audiences of the token, and otherwise should reject the token. A token issued for multiple audiences may be used to authenticate against any of the audiences listed but implies a high degree of trust between the target audiences."
            return self._set("audiences", value)

        @overload
        def bound_object_ref(
            self, value_or_callback: BoundObjectReference | None, /
        ) -> "TokenRequestSpec.Builder": ...

        @overload
        def bound_object_ref(
            self,
            value_or_callback: Callable[
                [BoundObjectReference.Builder],
                BoundObjectReference.Builder | BoundObjectReference,
            ],
            /,
        ) -> "TokenRequestSpec.Builder": ...

        @overload
        def bound_object_ref(
            self, value_or_callback: Never = ...
        ) -> "BoundObjectReference.BuilderContext": ...

        def bound_object_ref(self, value_or_callback=UNSET, /):
            "BoundObjectRef is a reference to an object that the token will be bound to. The token will only be valid for as long as the bound object exists. NOTE: The API server\u0027s TokenReview endpoint will validate the BoundObjectRef, but other audiences may not. Keep ExpirationSeconds small if you want prompt revocation."
            if self._in_context and value_or_callback is UNSET:
                context = BoundObjectReference.BuilderContext()
                context._parent_builder = self
                context._field_name = "bound_object_ref"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(BoundObjectReference.builder())
                if isinstance(output, BoundObjectReference.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("bound_object_ref", value)

        def expiration_seconds(self, value: int | None, /) -> Self:
            "ExpirationSeconds is the requested duration of validity of the request. The token issuer may return a token with a different validity duration so a client needs to check the \u0027expiration\u0027 field in a response."
            return self._set("expiration_seconds", value)

    class BuilderContext(BuilderContextBase["TokenRequestSpec.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = TokenRequestSpec.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for TokenRequestSpec."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["TokenRequestSpec", Builder]:
        return GenericListBuilder[TokenRequestSpec, TokenRequestSpec.Builder]()

    audiences: list[str]
    "Audiences are the intendend audiences of the token. A recipient of a token must identify themself with an identifier in the list of audiences of the token, and otherwise should reject the token. A token issued for multiple audiences may be used to authenticate against any of the audiences listed but implies a high degree of trust between the target audiences."
    bound_object_ref: Annotated[BoundObjectReference | None, Field(alias="boundObjectRef")] = None
    "BoundObjectRef is a reference to an object that the token will be bound to. The token will only be valid for as long as the bound object exists. NOTE: The API server\u0027s TokenReview endpoint will validate the BoundObjectRef, but other audiences may not. Keep ExpirationSeconds small if you want prompt revocation."
    expiration_seconds: Annotated[int | None, Field(alias="expirationSeconds")] = None
    "ExpirationSeconds is the requested duration of validity of the request. The token issuer may return a token with a different validity duration so a client needs to check the \u0027expiration\u0027 field in a response."


class TokenRequestStatus(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["TokenRequestStatus"]:
            return TokenRequestStatus

        def build(self) -> "TokenRequestStatus":
            return TokenRequestStatus(**self._attrs)

        @overload
        def expiration_timestamp(
            self, value_or_callback: Time, /
        ) -> "TokenRequestStatus.Builder": ...

        @overload
        def expiration_timestamp(
            self, value_or_callback: Callable[[Time.Builder], Time.Builder | Time], /
        ) -> "TokenRequestStatus.Builder": ...

        @overload
        def expiration_timestamp(self, value_or_callback: Never = ...) -> "Time.BuilderContext": ...

        def expiration_timestamp(self, value_or_callback=UNSET, /):
            "ExpirationTimestamp is the time of expiration of the returned token."
            if self._in_context and value_or_callback is UNSET:
                context = Time.BuilderContext()
                context._parent_builder = self
                context._field_name = "expiration_timestamp"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(Time.builder())
                if isinstance(output, Time.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("expiration_timestamp", value)

        def token(self, value: str, /) -> Self:
            "Token is the opaque bearer token."
            return self._set("token", value)

    class BuilderContext(BuilderContextBase["TokenRequestStatus.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = TokenRequestStatus.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for TokenRequestStatus."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["TokenRequestStatus", Builder]:
        return GenericListBuilder[TokenRequestStatus, TokenRequestStatus.Builder]()

    expiration_timestamp: Annotated[Time, Field(alias="expirationTimestamp")]
    "ExpirationTimestamp is the time of expiration of the returned token."
    token: str
    "Token is the opaque bearer token."


class TokenReviewSpec(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["TokenReviewSpec"]:
            return TokenReviewSpec

        def build(self) -> "TokenReviewSpec":
            return TokenReviewSpec(**self._attrs)

        def audiences(self, value: list[str] | None, /) -> Self:
            "Audiences is a list of the identifiers that the resource server presented with the token identifies as. Audience-aware token authenticators will verify that the token was intended for at least one of the audiences in this list. If no audiences are provided, the audience will default to the audience of the Kubernetes apiserver."
            return self._set("audiences", value)

        def token(self, value: str | None, /) -> Self:
            "Token is the opaque bearer token."
            return self._set("token", value)

    class BuilderContext(BuilderContextBase["TokenReviewSpec.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = TokenReviewSpec.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for TokenReviewSpec."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["TokenReviewSpec", Builder]:
        return GenericListBuilder[TokenReviewSpec, TokenReviewSpec.Builder]()

    audiences: list[str] | None = None
    "Audiences is a list of the identifiers that the resource server presented with the token identifies as. Audience-aware token authenticators will verify that the token was intended for at least one of the audiences in this list. If no audiences are provided, the audience will default to the audience of the Kubernetes apiserver."
    token: str | None = None
    "Token is the opaque bearer token."


class UserInfo(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["UserInfo"]:
            return UserInfo

        def build(self) -> "UserInfo":
            return UserInfo(**self._attrs)

        def extra(self, value: dict[str, list[str]] | None, /) -> Self:
            "Any additional information provided by the authenticator."
            return self._set("extra", value)

        def groups(self, value: list[str] | None, /) -> Self:
            "The names of groups this user is a part of."
            return self._set("groups", value)

        def uid(self, value: str | None, /) -> Self:
            "A unique value that identifies this user across time. If this user is deleted and another user by the same name is added, they will have different UIDs."
            return self._set("uid", value)

        def username(self, value: str | None, /) -> Self:
            "The name that uniquely identifies this user among all active users."
            return self._set("username", value)

    class BuilderContext(BuilderContextBase["UserInfo.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = UserInfo.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for UserInfo."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["UserInfo", Builder]:
        return GenericListBuilder[UserInfo, UserInfo.Builder]()

    extra: dict[str, list[str]] | None = None
    "Any additional information provided by the authenticator."
    groups: list[str] | None = None
    "The names of groups this user is a part of."
    uid: str | None = None
    "A unique value that identifies this user across time. If this user is deleted and another user by the same name is added, they will have different UIDs."
    username: str | None = None
    "The name that uniquely identifies this user among all active users."


class SelfSubjectReviewStatus(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["SelfSubjectReviewStatus"]:
            return SelfSubjectReviewStatus

        def build(self) -> "SelfSubjectReviewStatus":
            return SelfSubjectReviewStatus(**self._attrs)

        @overload
        def user_info(
            self, value_or_callback: UserInfo | None, /
        ) -> "SelfSubjectReviewStatus.Builder": ...

        @overload
        def user_info(
            self,
            value_or_callback: Callable[[UserInfo.Builder], UserInfo.Builder | UserInfo],
            /,
        ) -> "SelfSubjectReviewStatus.Builder": ...

        @overload
        def user_info(self, value_or_callback: Never = ...) -> "UserInfo.BuilderContext": ...

        def user_info(self, value_or_callback=UNSET, /):
            "User attributes of the user making this request."
            if self._in_context and value_or_callback is UNSET:
                context = UserInfo.BuilderContext()
                context._parent_builder = self
                context._field_name = "user_info"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(UserInfo.builder())
                if isinstance(output, UserInfo.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("user_info", value)

    class BuilderContext(BuilderContextBase["SelfSubjectReviewStatus.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = SelfSubjectReviewStatus.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for SelfSubjectReviewStatus."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["SelfSubjectReviewStatus", Builder]:
        return GenericListBuilder[SelfSubjectReviewStatus, SelfSubjectReviewStatus.Builder]()

    user_info: Annotated[UserInfo | None, Field(alias="userInfo")] = None
    "User attributes of the user making this request."


class TokenRequest(Resource):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["TokenRequest"]:
            return TokenRequest

        def build(self) -> "TokenRequest":
            return TokenRequest(**self._attrs)

        def api_version(self, value: Literal["authentication.k8s.io/v1"], /) -> Self:
            "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
            return self._set("api_version", value)

        def kind(self, value: Literal["TokenRequest"], /) -> Self:
            "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
            return self._set("kind", value)

        @overload
        def metadata(self, value_or_callback: ObjectMeta | None, /) -> "TokenRequest.Builder": ...

        @overload
        def metadata(
            self,
            value_or_callback: Callable[[ObjectMeta.Builder], ObjectMeta.Builder | ObjectMeta],
            /,
        ) -> "TokenRequest.Builder": ...

        @overload
        def metadata(self, value_or_callback: Never = ...) -> "ObjectMeta.BuilderContext": ...

        def metadata(self, value_or_callback=UNSET, /):
            "Standard object\u0027s metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata"
            if self._in_context and value_or_callback is UNSET:
                context = ObjectMeta.BuilderContext()
                context._parent_builder = self
                context._field_name = "metadata"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ObjectMeta.builder())
                if isinstance(output, ObjectMeta.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("metadata", value)

        @overload
        def spec(self, value_or_callback: TokenRequestSpec, /) -> "TokenRequest.Builder": ...

        @overload
        def spec(
            self,
            value_or_callback: Callable[
                [TokenRequestSpec.Builder], TokenRequestSpec.Builder | TokenRequestSpec
            ],
            /,
        ) -> "TokenRequest.Builder": ...

        @overload
        def spec(self, value_or_callback: Never = ...) -> "TokenRequestSpec.BuilderContext": ...

        def spec(self, value_or_callback=UNSET, /):
            "Spec holds information about the request being evaluated"
            if self._in_context and value_or_callback is UNSET:
                context = TokenRequestSpec.BuilderContext()
                context._parent_builder = self
                context._field_name = "spec"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(TokenRequestSpec.builder())
                if isinstance(output, TokenRequestSpec.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("spec", value)

        @overload
        def status(
            self, value_or_callback: TokenRequestStatus | None, /
        ) -> "TokenRequest.Builder": ...

        @overload
        def status(
            self,
            value_or_callback: Callable[
                [TokenRequestStatus.Builder],
                TokenRequestStatus.Builder | TokenRequestStatus,
            ],
            /,
        ) -> "TokenRequest.Builder": ...

        @overload
        def status(self, value_or_callback: Never = ...) -> "TokenRequestStatus.BuilderContext": ...

        def status(self, value_or_callback=UNSET, /):
            "Status is filled in by the server and indicates whether the token can be authenticated."
            if self._in_context and value_or_callback is UNSET:
                context = TokenRequestStatus.BuilderContext()
                context._parent_builder = self
                context._field_name = "status"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(TokenRequestStatus.builder())
                if isinstance(output, TokenRequestStatus.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("status", value)

    class BuilderContext(BuilderContextBase["TokenRequest.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = TokenRequest.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for TokenRequest."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["TokenRequest", Builder]:
        return GenericListBuilder[TokenRequest, TokenRequest.Builder]()

    api_version: Annotated[Literal["authentication.k8s.io/v1"], Field(alias="apiVersion")] = (
        "authentication.k8s.io/v1"
    )
    "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
    kind: Literal["TokenRequest"] = "TokenRequest"
    "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
    metadata: ObjectMeta | None = None
    "Standard object\u0027s metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata"
    spec: TokenRequestSpec
    "Spec holds information about the request being evaluated"
    status: TokenRequestStatus | None = None
    "Status is filled in by the server and indicates whether the token can be authenticated."


class TokenReviewStatus(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["TokenReviewStatus"]:
            return TokenReviewStatus

        def build(self) -> "TokenReviewStatus":
            return TokenReviewStatus(**self._attrs)

        def audiences(self, value: list[str] | None, /) -> Self:
            'Audiences are audience identifiers chosen by the authenticator that are compatible with both the TokenReview and token. An identifier is any identifier in the intersection of the TokenReviewSpec audiences and the token\u0027s audiences. A client of the TokenReview API that sets the spec.audiences field should validate that a compatible audience identifier is returned in the status.audiences field to ensure that the TokenReview server is audience aware. If a TokenReview returns an empty status.audience field where status.authenticated is "true", the token is valid against the audience of the Kubernetes API server.'
            return self._set("audiences", value)

        def authenticated(self, value: bool | None, /) -> Self:
            "Authenticated indicates that the token was associated with a known user."
            return self._set("authenticated", value)

        def error(self, value: str | None, /) -> Self:
            "Error indicates that the token couldn\u0027t be checked"
            return self._set("error", value)

        @overload
        def user(self, value_or_callback: UserInfo | None, /) -> "TokenReviewStatus.Builder": ...

        @overload
        def user(
            self,
            value_or_callback: Callable[[UserInfo.Builder], UserInfo.Builder | UserInfo],
            /,
        ) -> "TokenReviewStatus.Builder": ...

        @overload
        def user(self, value_or_callback: Never = ...) -> "UserInfo.BuilderContext": ...

        def user(self, value_or_callback=UNSET, /):
            "User is the UserInfo associated with the provided token."
            if self._in_context and value_or_callback is UNSET:
                context = UserInfo.BuilderContext()
                context._parent_builder = self
                context._field_name = "user"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(UserInfo.builder())
                if isinstance(output, UserInfo.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("user", value)

    class BuilderContext(BuilderContextBase["TokenReviewStatus.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = TokenReviewStatus.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for TokenReviewStatus."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["TokenReviewStatus", Builder]:
        return GenericListBuilder[TokenReviewStatus, TokenReviewStatus.Builder]()

    audiences: list[str] | None = None
    'Audiences are audience identifiers chosen by the authenticator that are compatible with both the TokenReview and token. An identifier is any identifier in the intersection of the TokenReviewSpec audiences and the token\u0027s audiences. A client of the TokenReview API that sets the spec.audiences field should validate that a compatible audience identifier is returned in the status.audiences field to ensure that the TokenReview server is audience aware. If a TokenReview returns an empty status.audience field where status.authenticated is "true", the token is valid against the audience of the Kubernetes API server.'
    authenticated: bool | None = None
    "Authenticated indicates that the token was associated with a known user."
    error: str | None = None
    "Error indicates that the token couldn\u0027t be checked"
    user: UserInfo | None = None
    "User is the UserInfo associated with the provided token."


class SelfSubjectReview(Resource):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["SelfSubjectReview"]:
            return SelfSubjectReview

        def build(self) -> "SelfSubjectReview":
            return SelfSubjectReview(**self._attrs)

        def api_version(self, value: Literal["authentication.k8s.io/v1"], /) -> Self:
            "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
            return self._set("api_version", value)

        def kind(self, value: Literal["SelfSubjectReview"], /) -> Self:
            "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
            return self._set("kind", value)

        @overload
        def metadata(
            self, value_or_callback: ObjectMeta | None, /
        ) -> "SelfSubjectReview.Builder": ...

        @overload
        def metadata(
            self,
            value_or_callback: Callable[[ObjectMeta.Builder], ObjectMeta.Builder | ObjectMeta],
            /,
        ) -> "SelfSubjectReview.Builder": ...

        @overload
        def metadata(self, value_or_callback: Never = ...) -> "ObjectMeta.BuilderContext": ...

        def metadata(self, value_or_callback=UNSET, /):
            "Standard object\u0027s metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata"
            if self._in_context and value_or_callback is UNSET:
                context = ObjectMeta.BuilderContext()
                context._parent_builder = self
                context._field_name = "metadata"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ObjectMeta.builder())
                if isinstance(output, ObjectMeta.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("metadata", value)

        @overload
        def status(
            self, value_or_callback: SelfSubjectReviewStatus | None, /
        ) -> "SelfSubjectReview.Builder": ...

        @overload
        def status(
            self,
            value_or_callback: Callable[
                [SelfSubjectReviewStatus.Builder],
                SelfSubjectReviewStatus.Builder | SelfSubjectReviewStatus,
            ],
            /,
        ) -> "SelfSubjectReview.Builder": ...

        @overload
        def status(
            self, value_or_callback: Never = ...
        ) -> "SelfSubjectReviewStatus.BuilderContext": ...

        def status(self, value_or_callback=UNSET, /):
            "Status is filled in by the server with the user attributes."
            if self._in_context and value_or_callback is UNSET:
                context = SelfSubjectReviewStatus.BuilderContext()
                context._parent_builder = self
                context._field_name = "status"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(SelfSubjectReviewStatus.builder())
                if isinstance(output, SelfSubjectReviewStatus.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("status", value)

    class BuilderContext(BuilderContextBase["SelfSubjectReview.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = SelfSubjectReview.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for SelfSubjectReview."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["SelfSubjectReview", Builder]:
        return GenericListBuilder[SelfSubjectReview, SelfSubjectReview.Builder]()

    api_version: Annotated[Literal["authentication.k8s.io/v1"], Field(alias="apiVersion")] = (
        "authentication.k8s.io/v1"
    )
    "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
    kind: Literal["SelfSubjectReview"] = "SelfSubjectReview"
    "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
    metadata: ObjectMeta | None = None
    "Standard object\u0027s metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata"
    status: SelfSubjectReviewStatus | None = None
    "Status is filled in by the server with the user attributes."


class TokenReview(Resource):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["TokenReview"]:
            return TokenReview

        def build(self) -> "TokenReview":
            return TokenReview(**self._attrs)

        def api_version(self, value: Literal["authentication.k8s.io/v1"], /) -> Self:
            "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
            return self._set("api_version", value)

        def kind(self, value: Literal["TokenReview"], /) -> Self:
            "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
            return self._set("kind", value)

        @overload
        def metadata(self, value_or_callback: ObjectMeta | None, /) -> "TokenReview.Builder": ...

        @overload
        def metadata(
            self,
            value_or_callback: Callable[[ObjectMeta.Builder], ObjectMeta.Builder | ObjectMeta],
            /,
        ) -> "TokenReview.Builder": ...

        @overload
        def metadata(self, value_or_callback: Never = ...) -> "ObjectMeta.BuilderContext": ...

        def metadata(self, value_or_callback=UNSET, /):
            "Standard object\u0027s metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata"
            if self._in_context and value_or_callback is UNSET:
                context = ObjectMeta.BuilderContext()
                context._parent_builder = self
                context._field_name = "metadata"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ObjectMeta.builder())
                if isinstance(output, ObjectMeta.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("metadata", value)

        @overload
        def spec(self, value_or_callback: TokenReviewSpec, /) -> "TokenReview.Builder": ...

        @overload
        def spec(
            self,
            value_or_callback: Callable[
                [TokenReviewSpec.Builder], TokenReviewSpec.Builder | TokenReviewSpec
            ],
            /,
        ) -> "TokenReview.Builder": ...

        @overload
        def spec(self, value_or_callback: Never = ...) -> "TokenReviewSpec.BuilderContext": ...

        def spec(self, value_or_callback=UNSET, /):
            "Spec holds information about the request being evaluated"
            if self._in_context and value_or_callback is UNSET:
                context = TokenReviewSpec.BuilderContext()
                context._parent_builder = self
                context._field_name = "spec"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(TokenReviewSpec.builder())
                if isinstance(output, TokenReviewSpec.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("spec", value)

        @overload
        def status(
            self, value_or_callback: TokenReviewStatus | None, /
        ) -> "TokenReview.Builder": ...

        @overload
        def status(
            self,
            value_or_callback: Callable[
                [TokenReviewStatus.Builder],
                TokenReviewStatus.Builder | TokenReviewStatus,
            ],
            /,
        ) -> "TokenReview.Builder": ...

        @overload
        def status(self, value_or_callback: Never = ...) -> "TokenReviewStatus.BuilderContext": ...

        def status(self, value_or_callback=UNSET, /):
            "Status is filled in by the server and indicates whether the request can be authenticated."
            if self._in_context and value_or_callback is UNSET:
                context = TokenReviewStatus.BuilderContext()
                context._parent_builder = self
                context._field_name = "status"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(TokenReviewStatus.builder())
                if isinstance(output, TokenReviewStatus.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("status", value)

    class BuilderContext(BuilderContextBase["TokenReview.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = TokenReview.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for TokenReview."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["TokenReview", Builder]:
        return GenericListBuilder[TokenReview, TokenReview.Builder]()

    api_version: Annotated[Literal["authentication.k8s.io/v1"], Field(alias="apiVersion")] = (
        "authentication.k8s.io/v1"
    )
    "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
    kind: Literal["TokenReview"] = "TokenReview"
    "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
    metadata: ObjectMeta | None = None
    "Standard object\u0027s metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata"
    spec: TokenReviewSpec
    "Spec holds information about the request being evaluated"
    status: TokenReviewStatus | None = None
    "Status is filled in by the server and indicates whether the request can be authenticated."
