# Generated by cloudcoil-model-codegen v0.7.0
# DO NOT EDIT

from typing import Annotated, Callable, Literal, overload

from cloudcoil.apimachinery import (
    FieldSelectorRequirement,
    LabelSelectorRequirement,
    ObjectMeta,
)
from cloudcoil.pydantic import (
    UNSET,
    BaseModel,
    BaseModelBuilder,
    BuilderContextBase,
    GenericListBuilder,
    ListBuilderContext,
    Never,
    Self,
)
from cloudcoil.resources import Resource
from pydantic import Field


class FieldSelectorAttributes(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["FieldSelectorAttributes"]:
            return FieldSelectorAttributes

        def build(self) -> "FieldSelectorAttributes":
            return FieldSelectorAttributes(**self._attrs)

        def raw_selector(self, value: str | None, /) -> Self:
            "rawSelector is the serialization of a field selector that would be included in a query parameter. Webhook implementations are encouraged to ignore rawSelector. The kube-apiserver\u0027s *SubjectAccessReview will parse the rawSelector as long as the requirements are not present."
            return self._set("raw_selector", value)

        @overload
        def requirements(
            self, value_or_callback: list[FieldSelectorRequirement] | None, /
        ) -> "FieldSelectorAttributes.Builder": ...

        @overload
        def requirements(
            self,
            value_or_callback: Callable[
                [GenericListBuilder[FieldSelectorRequirement, FieldSelectorRequirement.Builder]],
                GenericListBuilder[FieldSelectorRequirement, FieldSelectorRequirement.Builder]
                | list[FieldSelectorRequirement],
            ],
            /,
        ) -> "FieldSelectorAttributes.Builder": ...

        @overload
        def requirements(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[FieldSelectorRequirement.Builder]: ...

        def requirements(self, value_or_callback=UNSET, /):
            "requirements is the parsed interpretation of a field selector. All requirements must be met for a resource instance to match the selector. Webhook implementations should handle requirements, but how to handle them is up to the webhook. Since requirements can only limit the request, it is safe to authorize as unlimited request if the requirements are not understood."
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[FieldSelectorRequirement.Builder]()
                context._parent_builder = self
                context._field_name = "requirements"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(FieldSelectorRequirement.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("requirements", value)

    class BuilderContext(BuilderContextBase["FieldSelectorAttributes.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = FieldSelectorAttributes.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for FieldSelectorAttributes."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["FieldSelectorAttributes", Builder]:
        return GenericListBuilder[FieldSelectorAttributes, FieldSelectorAttributes.Builder]()

    raw_selector: Annotated[str | None, Field(alias="rawSelector")] = None
    "rawSelector is the serialization of a field selector that would be included in a query parameter. Webhook implementations are encouraged to ignore rawSelector. The kube-apiserver\u0027s *SubjectAccessReview will parse the rawSelector as long as the requirements are not present."
    requirements: list[FieldSelectorRequirement] | None = None
    "requirements is the parsed interpretation of a field selector. All requirements must be met for a resource instance to match the selector. Webhook implementations should handle requirements, but how to handle them is up to the webhook. Since requirements can only limit the request, it is safe to authorize as unlimited request if the requirements are not understood."


class LabelSelectorAttributes(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["LabelSelectorAttributes"]:
            return LabelSelectorAttributes

        def build(self) -> "LabelSelectorAttributes":
            return LabelSelectorAttributes(**self._attrs)

        def raw_selector(self, value: str | None, /) -> Self:
            "rawSelector is the serialization of a field selector that would be included in a query parameter. Webhook implementations are encouraged to ignore rawSelector. The kube-apiserver\u0027s *SubjectAccessReview will parse the rawSelector as long as the requirements are not present."
            return self._set("raw_selector", value)

        @overload
        def requirements(
            self, value_or_callback: list[LabelSelectorRequirement] | None, /
        ) -> "LabelSelectorAttributes.Builder": ...

        @overload
        def requirements(
            self,
            value_or_callback: Callable[
                [GenericListBuilder[LabelSelectorRequirement, LabelSelectorRequirement.Builder]],
                GenericListBuilder[LabelSelectorRequirement, LabelSelectorRequirement.Builder]
                | list[LabelSelectorRequirement],
            ],
            /,
        ) -> "LabelSelectorAttributes.Builder": ...

        @overload
        def requirements(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[LabelSelectorRequirement.Builder]: ...

        def requirements(self, value_or_callback=UNSET, /):
            "requirements is the parsed interpretation of a label selector. All requirements must be met for a resource instance to match the selector. Webhook implementations should handle requirements, but how to handle them is up to the webhook. Since requirements can only limit the request, it is safe to authorize as unlimited request if the requirements are not understood."
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[LabelSelectorRequirement.Builder]()
                context._parent_builder = self
                context._field_name = "requirements"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(LabelSelectorRequirement.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("requirements", value)

    class BuilderContext(BuilderContextBase["LabelSelectorAttributes.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = LabelSelectorAttributes.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for LabelSelectorAttributes."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["LabelSelectorAttributes", Builder]:
        return GenericListBuilder[LabelSelectorAttributes, LabelSelectorAttributes.Builder]()

    raw_selector: Annotated[str | None, Field(alias="rawSelector")] = None
    "rawSelector is the serialization of a field selector that would be included in a query parameter. Webhook implementations are encouraged to ignore rawSelector. The kube-apiserver\u0027s *SubjectAccessReview will parse the rawSelector as long as the requirements are not present."
    requirements: list[LabelSelectorRequirement] | None = None
    "requirements is the parsed interpretation of a label selector. All requirements must be met for a resource instance to match the selector. Webhook implementations should handle requirements, but how to handle them is up to the webhook. Since requirements can only limit the request, it is safe to authorize as unlimited request if the requirements are not understood."


class NonResourceAttributes(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["NonResourceAttributes"]:
            return NonResourceAttributes

        def build(self) -> "NonResourceAttributes":
            return NonResourceAttributes(**self._attrs)

        def path(self, value: str | None, /) -> Self:
            "path is the URL path of the request"
            return self._set("path", value)

        def verb(self, value: str | None, /) -> Self:
            "verb is the standard HTTP verb"
            return self._set("verb", value)

    class BuilderContext(BuilderContextBase["NonResourceAttributes.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = NonResourceAttributes.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for NonResourceAttributes."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["NonResourceAttributes", Builder]:
        return GenericListBuilder[NonResourceAttributes, NonResourceAttributes.Builder]()

    path: str | None = None
    "path is the URL path of the request"
    verb: str | None = None
    "verb is the standard HTTP verb"


class NonResourceRule(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["NonResourceRule"]:
            return NonResourceRule

        def build(self) -> "NonResourceRule":
            return NonResourceRule(**self._attrs)

        def non_resource_ur_ls(self, value: list[str] | None, /) -> Self:
            'nonResourceURLs is a set of partial urls that a user should have access to.  *s are allowed, but only as the full, final step in the path.  "*" means all.'
            return self._set("non_resource_ur_ls", value)

        def verbs(self, value: list[str], /) -> Self:
            'verbs is a list of kubernetes non-resource API verbs, like: get, post, put, delete, patch, head, options.  "*" means all.'
            return self._set("verbs", value)

    class BuilderContext(BuilderContextBase["NonResourceRule.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = NonResourceRule.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for NonResourceRule."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["NonResourceRule", Builder]:
        return GenericListBuilder[NonResourceRule, NonResourceRule.Builder]()

    non_resource_ur_ls: Annotated[list[str] | None, Field(alias="nonResourceURLs")] = None
    'nonResourceURLs is a set of partial urls that a user should have access to.  *s are allowed, but only as the full, final step in the path.  "*" means all.'
    verbs: list[str]
    'verbs is a list of kubernetes non-resource API verbs, like: get, post, put, delete, patch, head, options.  "*" means all.'


class ResourceAttributes(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["ResourceAttributes"]:
            return ResourceAttributes

        def build(self) -> "ResourceAttributes":
            return ResourceAttributes(**self._attrs)

        @overload
        def field_selector(
            self, value_or_callback: FieldSelectorAttributes | None, /
        ) -> "ResourceAttributes.Builder": ...

        @overload
        def field_selector(
            self,
            value_or_callback: Callable[
                [FieldSelectorAttributes.Builder],
                FieldSelectorAttributes.Builder | FieldSelectorAttributes,
            ],
            /,
        ) -> "ResourceAttributes.Builder": ...

        @overload
        def field_selector(
            self, value_or_callback: Never = ...
        ) -> "FieldSelectorAttributes.BuilderContext": ...

        def field_selector(self, value_or_callback=UNSET, /):
            "fieldSelector describes the limitation on access based on field.  It can only limit access, not broaden it."
            if self._in_context and value_or_callback is UNSET:
                context = FieldSelectorAttributes.BuilderContext()
                context._parent_builder = self
                context._field_name = "field_selector"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(FieldSelectorAttributes.builder())
                if isinstance(output, FieldSelectorAttributes.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("field_selector", value)

        def group(self, value: str | None, /) -> Self:
            'group is the API Group of the Resource.  "*" means all.'
            return self._set("group", value)

        @overload
        def label_selector(
            self, value_or_callback: LabelSelectorAttributes | None, /
        ) -> "ResourceAttributes.Builder": ...

        @overload
        def label_selector(
            self,
            value_or_callback: Callable[
                [LabelSelectorAttributes.Builder],
                LabelSelectorAttributes.Builder | LabelSelectorAttributes,
            ],
            /,
        ) -> "ResourceAttributes.Builder": ...

        @overload
        def label_selector(
            self, value_or_callback: Never = ...
        ) -> "LabelSelectorAttributes.BuilderContext": ...

        def label_selector(self, value_or_callback=UNSET, /):
            "labelSelector describes the limitation on access based on labels.  It can only limit access, not broaden it."
            if self._in_context and value_or_callback is UNSET:
                context = LabelSelectorAttributes.BuilderContext()
                context._parent_builder = self
                context._field_name = "label_selector"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(LabelSelectorAttributes.builder())
                if isinstance(output, LabelSelectorAttributes.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("label_selector", value)

        def name(self, value: str | None, /) -> Self:
            'name is the name of the resource being requested for a "get" or deleted for a "delete". "" (empty) means all.'
            return self._set("name", value)

        def namespace(self, value: str | None, /) -> Self:
            'namespace is the namespace of the action being requested.  Currently, there is no distinction between no namespace and all namespaces "" (empty) is defaulted for LocalSubjectAccessReviews "" (empty) is empty for cluster-scoped resources "" (empty) means "all" for namespace scoped resources from a SubjectAccessReview or SelfSubjectAccessReview'
            return self._set("namespace", value)

        def resource(self, value: str | None, /) -> Self:
            'resource is one of the existing resource types.  "*" means all.'
            return self._set("resource", value)

        def subresource(self, value: str | None, /) -> Self:
            'subresource is one of the existing resource types.  "" means none.'
            return self._set("subresource", value)

        def verb(self, value: str | None, /) -> Self:
            'verb is a kubernetes resource API verb, like: get, list, watch, create, update, delete, proxy.  "*" means all.'
            return self._set("verb", value)

        def version(self, value: str | None, /) -> Self:
            'version is the API Version of the Resource.  "*" means all.'
            return self._set("version", value)

    class BuilderContext(BuilderContextBase["ResourceAttributes.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = ResourceAttributes.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ResourceAttributes."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["ResourceAttributes", Builder]:
        return GenericListBuilder[ResourceAttributes, ResourceAttributes.Builder]()

    field_selector: Annotated[FieldSelectorAttributes | None, Field(alias="fieldSelector")] = None
    "fieldSelector describes the limitation on access based on field.  It can only limit access, not broaden it."
    group: str | None = None
    'group is the API Group of the Resource.  "*" means all.'
    label_selector: Annotated[LabelSelectorAttributes | None, Field(alias="labelSelector")] = None
    "labelSelector describes the limitation on access based on labels.  It can only limit access, not broaden it."
    name: str | None = None
    'name is the name of the resource being requested for a "get" or deleted for a "delete". "" (empty) means all.'
    namespace: str | None = None
    'namespace is the namespace of the action being requested.  Currently, there is no distinction between no namespace and all namespaces "" (empty) is defaulted for LocalSubjectAccessReviews "" (empty) is empty for cluster-scoped resources "" (empty) means "all" for namespace scoped resources from a SubjectAccessReview or SelfSubjectAccessReview'
    resource: str | None = None
    'resource is one of the existing resource types.  "*" means all.'
    subresource: str | None = None
    'subresource is one of the existing resource types.  "" means none.'
    verb: str | None = None
    'verb is a kubernetes resource API verb, like: get, list, watch, create, update, delete, proxy.  "*" means all.'
    version: str | None = None
    'version is the API Version of the Resource.  "*" means all.'


class ResourceRule(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["ResourceRule"]:
            return ResourceRule

        def build(self) -> "ResourceRule":
            return ResourceRule(**self._attrs)

        def api_groups(self, value: list[str] | None, /) -> Self:
            'apiGroups is the name of the APIGroup that contains the resources.  If multiple API groups are specified, any action requested against one of the enumerated resources in any API group will be allowed.  "*" means all.'
            return self._set("api_groups", value)

        def resource_names(self, value: list[str] | None, /) -> Self:
            'resourceNames is an optional white list of names that the rule applies to.  An empty set means that everything is allowed.  "*" means all.'
            return self._set("resource_names", value)

        def resources(self, value: list[str] | None, /) -> Self:
            'resources is a list of resources this rule applies to.  "*" means all in the specified apiGroups.\n "*/foo" represents the subresource \u0027foo\u0027 for all resources in the specified apiGroups.'
            return self._set("resources", value)

        def verbs(self, value: list[str], /) -> Self:
            'verbs is a list of kubernetes resource API verbs, like: get, list, watch, create, update, delete, proxy.  "*" means all.'
            return self._set("verbs", value)

    class BuilderContext(BuilderContextBase["ResourceRule.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = ResourceRule.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ResourceRule."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["ResourceRule", Builder]:
        return GenericListBuilder[ResourceRule, ResourceRule.Builder]()

    api_groups: Annotated[list[str] | None, Field(alias="apiGroups")] = None
    'apiGroups is the name of the APIGroup that contains the resources.  If multiple API groups are specified, any action requested against one of the enumerated resources in any API group will be allowed.  "*" means all.'
    resource_names: Annotated[list[str] | None, Field(alias="resourceNames")] = None
    'resourceNames is an optional white list of names that the rule applies to.  An empty set means that everything is allowed.  "*" means all.'
    resources: list[str] | None = None
    'resources is a list of resources this rule applies to.  "*" means all in the specified apiGroups.\n "*/foo" represents the subresource \u0027foo\u0027 for all resources in the specified apiGroups.'
    verbs: list[str]
    'verbs is a list of kubernetes resource API verbs, like: get, list, watch, create, update, delete, proxy.  "*" means all.'


class SelfSubjectAccessReviewSpec(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["SelfSubjectAccessReviewSpec"]:
            return SelfSubjectAccessReviewSpec

        def build(self) -> "SelfSubjectAccessReviewSpec":
            return SelfSubjectAccessReviewSpec(**self._attrs)

        @overload
        def non_resource_attributes(
            self, value_or_callback: NonResourceAttributes | None, /
        ) -> "SelfSubjectAccessReviewSpec.Builder": ...

        @overload
        def non_resource_attributes(
            self,
            value_or_callback: Callable[
                [NonResourceAttributes.Builder],
                NonResourceAttributes.Builder | NonResourceAttributes,
            ],
            /,
        ) -> "SelfSubjectAccessReviewSpec.Builder": ...

        @overload
        def non_resource_attributes(
            self, value_or_callback: Never = ...
        ) -> "NonResourceAttributes.BuilderContext": ...

        def non_resource_attributes(self, value_or_callback=UNSET, /):
            "nonResourceAttributes describes information for a non-resource access request"
            if self._in_context and value_or_callback is UNSET:
                context = NonResourceAttributes.BuilderContext()
                context._parent_builder = self
                context._field_name = "non_resource_attributes"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(NonResourceAttributes.builder())
                if isinstance(output, NonResourceAttributes.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("non_resource_attributes", value)

        @overload
        def resource_attributes(
            self, value_or_callback: ResourceAttributes | None, /
        ) -> "SelfSubjectAccessReviewSpec.Builder": ...

        @overload
        def resource_attributes(
            self,
            value_or_callback: Callable[
                [ResourceAttributes.Builder],
                ResourceAttributes.Builder | ResourceAttributes,
            ],
            /,
        ) -> "SelfSubjectAccessReviewSpec.Builder": ...

        @overload
        def resource_attributes(
            self, value_or_callback: Never = ...
        ) -> "ResourceAttributes.BuilderContext": ...

        def resource_attributes(self, value_or_callback=UNSET, /):
            "resourceAttributes describes information for a resource access request"
            if self._in_context and value_or_callback is UNSET:
                context = ResourceAttributes.BuilderContext()
                context._parent_builder = self
                context._field_name = "resource_attributes"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ResourceAttributes.builder())
                if isinstance(output, ResourceAttributes.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("resource_attributes", value)

    class BuilderContext(BuilderContextBase["SelfSubjectAccessReviewSpec.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = SelfSubjectAccessReviewSpec.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for SelfSubjectAccessReviewSpec."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["SelfSubjectAccessReviewSpec", Builder]:
        return GenericListBuilder[
            SelfSubjectAccessReviewSpec, SelfSubjectAccessReviewSpec.Builder
        ]()

    non_resource_attributes: Annotated[
        NonResourceAttributes | None, Field(alias="nonResourceAttributes")
    ] = None
    "nonResourceAttributes describes information for a non-resource access request"
    resource_attributes: Annotated[ResourceAttributes | None, Field(alias="resourceAttributes")] = (
        None
    )
    "resourceAttributes describes information for a resource access request"


class SelfSubjectRulesReviewSpec(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["SelfSubjectRulesReviewSpec"]:
            return SelfSubjectRulesReviewSpec

        def build(self) -> "SelfSubjectRulesReviewSpec":
            return SelfSubjectRulesReviewSpec(**self._attrs)

        def namespace(self, value: str | None, /) -> Self:
            "namespace to evaluate rules for. Required."
            return self._set("namespace", value)

    class BuilderContext(BuilderContextBase["SelfSubjectRulesReviewSpec.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = SelfSubjectRulesReviewSpec.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for SelfSubjectRulesReviewSpec."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["SelfSubjectRulesReviewSpec", Builder]:
        return GenericListBuilder[SelfSubjectRulesReviewSpec, SelfSubjectRulesReviewSpec.Builder]()

    namespace: str | None = None
    "namespace to evaluate rules for. Required."


class SubjectAccessReviewSpec(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["SubjectAccessReviewSpec"]:
            return SubjectAccessReviewSpec

        def build(self) -> "SubjectAccessReviewSpec":
            return SubjectAccessReviewSpec(**self._attrs)

        def extra(self, value: dict[str, list[str]] | None, /) -> Self:
            "extra corresponds to the user.Info.GetExtra() method from the authenticator.  Since that is input to the authorizer it needs a reflection here."
            return self._set("extra", value)

        def groups(self, value: list[str] | None, /) -> Self:
            "groups is the groups you\u0027re testing for."
            return self._set("groups", value)

        @overload
        def non_resource_attributes(
            self, value_or_callback: NonResourceAttributes | None, /
        ) -> "SubjectAccessReviewSpec.Builder": ...

        @overload
        def non_resource_attributes(
            self,
            value_or_callback: Callable[
                [NonResourceAttributes.Builder],
                NonResourceAttributes.Builder | NonResourceAttributes,
            ],
            /,
        ) -> "SubjectAccessReviewSpec.Builder": ...

        @overload
        def non_resource_attributes(
            self, value_or_callback: Never = ...
        ) -> "NonResourceAttributes.BuilderContext": ...

        def non_resource_attributes(self, value_or_callback=UNSET, /):
            "nonResourceAttributes describes information for a non-resource access request"
            if self._in_context and value_or_callback is UNSET:
                context = NonResourceAttributes.BuilderContext()
                context._parent_builder = self
                context._field_name = "non_resource_attributes"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(NonResourceAttributes.builder())
                if isinstance(output, NonResourceAttributes.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("non_resource_attributes", value)

        @overload
        def resource_attributes(
            self, value_or_callback: ResourceAttributes | None, /
        ) -> "SubjectAccessReviewSpec.Builder": ...

        @overload
        def resource_attributes(
            self,
            value_or_callback: Callable[
                [ResourceAttributes.Builder],
                ResourceAttributes.Builder | ResourceAttributes,
            ],
            /,
        ) -> "SubjectAccessReviewSpec.Builder": ...

        @overload
        def resource_attributes(
            self, value_or_callback: Never = ...
        ) -> "ResourceAttributes.BuilderContext": ...

        def resource_attributes(self, value_or_callback=UNSET, /):
            "resourceAttributes describes information for a resource access request"
            if self._in_context and value_or_callback is UNSET:
                context = ResourceAttributes.BuilderContext()
                context._parent_builder = self
                context._field_name = "resource_attributes"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ResourceAttributes.builder())
                if isinstance(output, ResourceAttributes.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("resource_attributes", value)

        def uid(self, value: str | None, /) -> Self:
            "uid information about the requesting user."
            return self._set("uid", value)

        def user(self, value: str | None, /) -> Self:
            'user is the user you\u0027re testing for. If you specify "User" but not "Groups", then is it interpreted as "What if User were not a member of any groups'
            return self._set("user", value)

    class BuilderContext(BuilderContextBase["SubjectAccessReviewSpec.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = SubjectAccessReviewSpec.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for SubjectAccessReviewSpec."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["SubjectAccessReviewSpec", Builder]:
        return GenericListBuilder[SubjectAccessReviewSpec, SubjectAccessReviewSpec.Builder]()

    extra: dict[str, list[str]] | None = None
    "extra corresponds to the user.Info.GetExtra() method from the authenticator.  Since that is input to the authorizer it needs a reflection here."
    groups: list[str] | None = None
    "groups is the groups you\u0027re testing for."
    non_resource_attributes: Annotated[
        NonResourceAttributes | None, Field(alias="nonResourceAttributes")
    ] = None
    "nonResourceAttributes describes information for a non-resource access request"
    resource_attributes: Annotated[ResourceAttributes | None, Field(alias="resourceAttributes")] = (
        None
    )
    "resourceAttributes describes information for a resource access request"
    uid: str | None = None
    "uid information about the requesting user."
    user: str | None = None
    'user is the user you\u0027re testing for. If you specify "User" but not "Groups", then is it interpreted as "What if User were not a member of any groups'


class SubjectAccessReviewStatus(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["SubjectAccessReviewStatus"]:
            return SubjectAccessReviewStatus

        def build(self) -> "SubjectAccessReviewStatus":
            return SubjectAccessReviewStatus(**self._attrs)

        def allowed(self, value: bool, /) -> Self:
            "allowed is required. True if the action would be allowed, false otherwise."
            return self._set("allowed", value)

        def denied(self, value: bool | None, /) -> Self:
            "denied is optional. True if the action would be denied, otherwise false. If both allowed is false and denied is false, then the authorizer has no opinion on whether to authorize the action. Denied may not be true if Allowed is true."
            return self._set("denied", value)

        def evaluation_error(self, value: str | None, /) -> Self:
            "evaluationError is an indication that some error occurred during the authorization check. It is entirely possible to get an error and be able to continue determine authorization status in spite of it. For instance, RBAC can be missing a role, but enough roles are still present and bound to reason about the request."
            return self._set("evaluation_error", value)

        def reason(self, value: str | None, /) -> Self:
            "reason is optional.  It indicates why a request was allowed or denied."
            return self._set("reason", value)

    class BuilderContext(BuilderContextBase["SubjectAccessReviewStatus.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = SubjectAccessReviewStatus.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for SubjectAccessReviewStatus."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["SubjectAccessReviewStatus", Builder]:
        return GenericListBuilder[SubjectAccessReviewStatus, SubjectAccessReviewStatus.Builder]()

    allowed: bool
    "allowed is required. True if the action would be allowed, false otherwise."
    denied: bool | None = None
    "denied is optional. True if the action would be denied, otherwise false. If both allowed is false and denied is false, then the authorizer has no opinion on whether to authorize the action. Denied may not be true if Allowed is true."
    evaluation_error: Annotated[str | None, Field(alias="evaluationError")] = None
    "evaluationError is an indication that some error occurred during the authorization check. It is entirely possible to get an error and be able to continue determine authorization status in spite of it. For instance, RBAC can be missing a role, but enough roles are still present and bound to reason about the request."
    reason: str | None = None
    "reason is optional.  It indicates why a request was allowed or denied."


class SubjectRulesReviewStatus(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["SubjectRulesReviewStatus"]:
            return SubjectRulesReviewStatus

        def build(self) -> "SubjectRulesReviewStatus":
            return SubjectRulesReviewStatus(**self._attrs)

        def evaluation_error(self, value: str | None, /) -> Self:
            "evaluationError can appear in combination with Rules. It indicates an error occurred during rule evaluation, such as an authorizer that doesn\u0027t support rule evaluation, and that ResourceRules and/or NonResourceRules may be incomplete."
            return self._set("evaluation_error", value)

        def incomplete(self, value: bool, /) -> Self:
            "incomplete is true when the rules returned by this call are incomplete. This is most commonly encountered when an authorizer, such as an external authorizer, doesn\u0027t support rules evaluation."
            return self._set("incomplete", value)

        @overload
        def non_resource_rules(
            self, value_or_callback: list[NonResourceRule], /
        ) -> "SubjectRulesReviewStatus.Builder": ...

        @overload
        def non_resource_rules(
            self,
            value_or_callback: Callable[
                [GenericListBuilder[NonResourceRule, NonResourceRule.Builder]],
                GenericListBuilder[NonResourceRule, NonResourceRule.Builder]
                | list[NonResourceRule],
            ],
            /,
        ) -> "SubjectRulesReviewStatus.Builder": ...

        @overload
        def non_resource_rules(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[NonResourceRule.Builder]: ...

        def non_resource_rules(self, value_or_callback=UNSET, /):
            "nonResourceRules is the list of actions the subject is allowed to perform on non-resources. The list ordering isn\u0027t significant, may contain duplicates, and possibly be incomplete."
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[NonResourceRule.Builder]()
                context._parent_builder = self
                context._field_name = "non_resource_rules"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(NonResourceRule.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("non_resource_rules", value)

        @overload
        def resource_rules(
            self, value_or_callback: list[ResourceRule], /
        ) -> "SubjectRulesReviewStatus.Builder": ...

        @overload
        def resource_rules(
            self,
            value_or_callback: Callable[
                [GenericListBuilder[ResourceRule, ResourceRule.Builder]],
                GenericListBuilder[ResourceRule, ResourceRule.Builder] | list[ResourceRule],
            ],
            /,
        ) -> "SubjectRulesReviewStatus.Builder": ...

        @overload
        def resource_rules(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[ResourceRule.Builder]: ...

        def resource_rules(self, value_or_callback=UNSET, /):
            "resourceRules is the list of actions the subject is allowed to perform on resources. The list ordering isn\u0027t significant, may contain duplicates, and possibly be incomplete."
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[ResourceRule.Builder]()
                context._parent_builder = self
                context._field_name = "resource_rules"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ResourceRule.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("resource_rules", value)

    class BuilderContext(BuilderContextBase["SubjectRulesReviewStatus.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = SubjectRulesReviewStatus.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for SubjectRulesReviewStatus."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["SubjectRulesReviewStatus", Builder]:
        return GenericListBuilder[SubjectRulesReviewStatus, SubjectRulesReviewStatus.Builder]()

    evaluation_error: Annotated[str | None, Field(alias="evaluationError")] = None
    "evaluationError can appear in combination with Rules. It indicates an error occurred during rule evaluation, such as an authorizer that doesn\u0027t support rule evaluation, and that ResourceRules and/or NonResourceRules may be incomplete."
    incomplete: bool
    "incomplete is true when the rules returned by this call are incomplete. This is most commonly encountered when an authorizer, such as an external authorizer, doesn\u0027t support rules evaluation."
    non_resource_rules: Annotated[list[NonResourceRule], Field(alias="nonResourceRules")]
    "nonResourceRules is the list of actions the subject is allowed to perform on non-resources. The list ordering isn\u0027t significant, may contain duplicates, and possibly be incomplete."
    resource_rules: Annotated[list[ResourceRule], Field(alias="resourceRules")]
    "resourceRules is the list of actions the subject is allowed to perform on resources. The list ordering isn\u0027t significant, may contain duplicates, and possibly be incomplete."


class LocalSubjectAccessReview(Resource):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["LocalSubjectAccessReview"]:
            return LocalSubjectAccessReview

        def build(self) -> "LocalSubjectAccessReview":
            return LocalSubjectAccessReview(**self._attrs)

        def api_version(self, value: Literal["authorization.k8s.io/v1"], /) -> Self:
            "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
            return self._set("api_version", value)

        def kind(self, value: Literal["LocalSubjectAccessReview"], /) -> Self:
            "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
            return self._set("kind", value)

        @overload
        def metadata(
            self, value_or_callback: ObjectMeta | None, /
        ) -> "LocalSubjectAccessReview.Builder": ...

        @overload
        def metadata(
            self,
            value_or_callback: Callable[[ObjectMeta.Builder], ObjectMeta.Builder | ObjectMeta],
            /,
        ) -> "LocalSubjectAccessReview.Builder": ...

        @overload
        def metadata(self, value_or_callback: Never = ...) -> "ObjectMeta.BuilderContext": ...

        def metadata(self, value_or_callback=UNSET, /):
            "metadata is the standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata"
            if self._in_context and value_or_callback is UNSET:
                context = ObjectMeta.BuilderContext()
                context._parent_builder = self
                context._field_name = "metadata"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ObjectMeta.builder())
                if isinstance(output, ObjectMeta.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("metadata", value)

        @overload
        def spec(
            self, value_or_callback: SubjectAccessReviewSpec, /
        ) -> "LocalSubjectAccessReview.Builder": ...

        @overload
        def spec(
            self,
            value_or_callback: Callable[
                [SubjectAccessReviewSpec.Builder],
                SubjectAccessReviewSpec.Builder | SubjectAccessReviewSpec,
            ],
            /,
        ) -> "LocalSubjectAccessReview.Builder": ...

        @overload
        def spec(
            self, value_or_callback: Never = ...
        ) -> "SubjectAccessReviewSpec.BuilderContext": ...

        def spec(self, value_or_callback=UNSET, /):
            "spec holds information about the request being evaluated.  spec.namespace must be equal to the namespace you made the request against.  If empty, it is defaulted."
            if self._in_context and value_or_callback is UNSET:
                context = SubjectAccessReviewSpec.BuilderContext()
                context._parent_builder = self
                context._field_name = "spec"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(SubjectAccessReviewSpec.builder())
                if isinstance(output, SubjectAccessReviewSpec.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("spec", value)

        @overload
        def status(
            self, value_or_callback: SubjectAccessReviewStatus | None, /
        ) -> "LocalSubjectAccessReview.Builder": ...

        @overload
        def status(
            self,
            value_or_callback: Callable[
                [SubjectAccessReviewStatus.Builder],
                SubjectAccessReviewStatus.Builder | SubjectAccessReviewStatus,
            ],
            /,
        ) -> "LocalSubjectAccessReview.Builder": ...

        @overload
        def status(
            self, value_or_callback: Never = ...
        ) -> "SubjectAccessReviewStatus.BuilderContext": ...

        def status(self, value_or_callback=UNSET, /):
            "status is filled in by the server and indicates whether the request is allowed or not"
            if self._in_context and value_or_callback is UNSET:
                context = SubjectAccessReviewStatus.BuilderContext()
                context._parent_builder = self
                context._field_name = "status"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(SubjectAccessReviewStatus.builder())
                if isinstance(output, SubjectAccessReviewStatus.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("status", value)

    class BuilderContext(BuilderContextBase["LocalSubjectAccessReview.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = LocalSubjectAccessReview.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for LocalSubjectAccessReview."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["LocalSubjectAccessReview", Builder]:
        return GenericListBuilder[LocalSubjectAccessReview, LocalSubjectAccessReview.Builder]()

    api_version: Annotated[Literal["authorization.k8s.io/v1"], Field(alias="apiVersion")] = (
        "authorization.k8s.io/v1"
    )
    "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
    kind: Literal["LocalSubjectAccessReview"] = "LocalSubjectAccessReview"
    "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
    metadata: ObjectMeta | None = None
    "metadata is the standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata"
    spec: SubjectAccessReviewSpec
    "spec holds information about the request being evaluated.  spec.namespace must be equal to the namespace you made the request against.  If empty, it is defaulted."
    status: SubjectAccessReviewStatus | None = None
    "status is filled in by the server and indicates whether the request is allowed or not"


class SelfSubjectAccessReview(Resource):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["SelfSubjectAccessReview"]:
            return SelfSubjectAccessReview

        def build(self) -> "SelfSubjectAccessReview":
            return SelfSubjectAccessReview(**self._attrs)

        def api_version(self, value: Literal["authorization.k8s.io/v1"], /) -> Self:
            "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
            return self._set("api_version", value)

        def kind(self, value: Literal["SelfSubjectAccessReview"], /) -> Self:
            "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
            return self._set("kind", value)

        @overload
        def metadata(
            self, value_or_callback: ObjectMeta | None, /
        ) -> "SelfSubjectAccessReview.Builder": ...

        @overload
        def metadata(
            self,
            value_or_callback: Callable[[ObjectMeta.Builder], ObjectMeta.Builder | ObjectMeta],
            /,
        ) -> "SelfSubjectAccessReview.Builder": ...

        @overload
        def metadata(self, value_or_callback: Never = ...) -> "ObjectMeta.BuilderContext": ...

        def metadata(self, value_or_callback=UNSET, /):
            "metadata is the standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata"
            if self._in_context and value_or_callback is UNSET:
                context = ObjectMeta.BuilderContext()
                context._parent_builder = self
                context._field_name = "metadata"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ObjectMeta.builder())
                if isinstance(output, ObjectMeta.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("metadata", value)

        @overload
        def spec(
            self, value_or_callback: SelfSubjectAccessReviewSpec, /
        ) -> "SelfSubjectAccessReview.Builder": ...

        @overload
        def spec(
            self,
            value_or_callback: Callable[
                [SelfSubjectAccessReviewSpec.Builder],
                SelfSubjectAccessReviewSpec.Builder | SelfSubjectAccessReviewSpec,
            ],
            /,
        ) -> "SelfSubjectAccessReview.Builder": ...

        @overload
        def spec(
            self, value_or_callback: Never = ...
        ) -> "SelfSubjectAccessReviewSpec.BuilderContext": ...

        def spec(self, value_or_callback=UNSET, /):
            "spec holds information about the request being evaluated.  user and groups must be empty"
            if self._in_context and value_or_callback is UNSET:
                context = SelfSubjectAccessReviewSpec.BuilderContext()
                context._parent_builder = self
                context._field_name = "spec"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(SelfSubjectAccessReviewSpec.builder())
                if isinstance(output, SelfSubjectAccessReviewSpec.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("spec", value)

        @overload
        def status(
            self, value_or_callback: SubjectAccessReviewStatus | None, /
        ) -> "SelfSubjectAccessReview.Builder": ...

        @overload
        def status(
            self,
            value_or_callback: Callable[
                [SubjectAccessReviewStatus.Builder],
                SubjectAccessReviewStatus.Builder | SubjectAccessReviewStatus,
            ],
            /,
        ) -> "SelfSubjectAccessReview.Builder": ...

        @overload
        def status(
            self, value_or_callback: Never = ...
        ) -> "SubjectAccessReviewStatus.BuilderContext": ...

        def status(self, value_or_callback=UNSET, /):
            "status is filled in by the server and indicates whether the request is allowed or not"
            if self._in_context and value_or_callback is UNSET:
                context = SubjectAccessReviewStatus.BuilderContext()
                context._parent_builder = self
                context._field_name = "status"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(SubjectAccessReviewStatus.builder())
                if isinstance(output, SubjectAccessReviewStatus.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("status", value)

    class BuilderContext(BuilderContextBase["SelfSubjectAccessReview.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = SelfSubjectAccessReview.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for SelfSubjectAccessReview."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["SelfSubjectAccessReview", Builder]:
        return GenericListBuilder[SelfSubjectAccessReview, SelfSubjectAccessReview.Builder]()

    api_version: Annotated[Literal["authorization.k8s.io/v1"], Field(alias="apiVersion")] = (
        "authorization.k8s.io/v1"
    )
    "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
    kind: Literal["SelfSubjectAccessReview"] = "SelfSubjectAccessReview"
    "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
    metadata: ObjectMeta | None = None
    "metadata is the standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata"
    spec: SelfSubjectAccessReviewSpec
    "spec holds information about the request being evaluated.  user and groups must be empty"
    status: SubjectAccessReviewStatus | None = None
    "status is filled in by the server and indicates whether the request is allowed or not"


class SelfSubjectRulesReview(Resource):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["SelfSubjectRulesReview"]:
            return SelfSubjectRulesReview

        def build(self) -> "SelfSubjectRulesReview":
            return SelfSubjectRulesReview(**self._attrs)

        def api_version(self, value: Literal["authorization.k8s.io/v1"], /) -> Self:
            "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
            return self._set("api_version", value)

        def kind(self, value: Literal["SelfSubjectRulesReview"], /) -> Self:
            "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
            return self._set("kind", value)

        @overload
        def metadata(
            self, value_or_callback: ObjectMeta | None, /
        ) -> "SelfSubjectRulesReview.Builder": ...

        @overload
        def metadata(
            self,
            value_or_callback: Callable[[ObjectMeta.Builder], ObjectMeta.Builder | ObjectMeta],
            /,
        ) -> "SelfSubjectRulesReview.Builder": ...

        @overload
        def metadata(self, value_or_callback: Never = ...) -> "ObjectMeta.BuilderContext": ...

        def metadata(self, value_or_callback=UNSET, /):
            "metadata is the standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata"
            if self._in_context and value_or_callback is UNSET:
                context = ObjectMeta.BuilderContext()
                context._parent_builder = self
                context._field_name = "metadata"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ObjectMeta.builder())
                if isinstance(output, ObjectMeta.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("metadata", value)

        @overload
        def spec(
            self, value_or_callback: SelfSubjectRulesReviewSpec, /
        ) -> "SelfSubjectRulesReview.Builder": ...

        @overload
        def spec(
            self,
            value_or_callback: Callable[
                [SelfSubjectRulesReviewSpec.Builder],
                SelfSubjectRulesReviewSpec.Builder | SelfSubjectRulesReviewSpec,
            ],
            /,
        ) -> "SelfSubjectRulesReview.Builder": ...

        @overload
        def spec(
            self, value_or_callback: Never = ...
        ) -> "SelfSubjectRulesReviewSpec.BuilderContext": ...

        def spec(self, value_or_callback=UNSET, /):
            "spec holds information about the request being evaluated."
            if self._in_context and value_or_callback is UNSET:
                context = SelfSubjectRulesReviewSpec.BuilderContext()
                context._parent_builder = self
                context._field_name = "spec"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(SelfSubjectRulesReviewSpec.builder())
                if isinstance(output, SelfSubjectRulesReviewSpec.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("spec", value)

        @overload
        def status(
            self, value_or_callback: SubjectRulesReviewStatus | None, /
        ) -> "SelfSubjectRulesReview.Builder": ...

        @overload
        def status(
            self,
            value_or_callback: Callable[
                [SubjectRulesReviewStatus.Builder],
                SubjectRulesReviewStatus.Builder | SubjectRulesReviewStatus,
            ],
            /,
        ) -> "SelfSubjectRulesReview.Builder": ...

        @overload
        def status(
            self, value_or_callback: Never = ...
        ) -> "SubjectRulesReviewStatus.BuilderContext": ...

        def status(self, value_or_callback=UNSET, /):
            "status is filled in by the server and indicates the set of actions a user can perform."
            if self._in_context and value_or_callback is UNSET:
                context = SubjectRulesReviewStatus.BuilderContext()
                context._parent_builder = self
                context._field_name = "status"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(SubjectRulesReviewStatus.builder())
                if isinstance(output, SubjectRulesReviewStatus.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("status", value)

    class BuilderContext(BuilderContextBase["SelfSubjectRulesReview.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = SelfSubjectRulesReview.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for SelfSubjectRulesReview."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["SelfSubjectRulesReview", Builder]:
        return GenericListBuilder[SelfSubjectRulesReview, SelfSubjectRulesReview.Builder]()

    api_version: Annotated[Literal["authorization.k8s.io/v1"], Field(alias="apiVersion")] = (
        "authorization.k8s.io/v1"
    )
    "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
    kind: Literal["SelfSubjectRulesReview"] = "SelfSubjectRulesReview"
    "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
    metadata: ObjectMeta | None = None
    "metadata is the standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata"
    spec: SelfSubjectRulesReviewSpec
    "spec holds information about the request being evaluated."
    status: SubjectRulesReviewStatus | None = None
    "status is filled in by the server and indicates the set of actions a user can perform."


class SubjectAccessReview(Resource):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["SubjectAccessReview"]:
            return SubjectAccessReview

        def build(self) -> "SubjectAccessReview":
            return SubjectAccessReview(**self._attrs)

        def api_version(self, value: Literal["authorization.k8s.io/v1"], /) -> Self:
            "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
            return self._set("api_version", value)

        def kind(self, value: Literal["SubjectAccessReview"], /) -> Self:
            "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
            return self._set("kind", value)

        @overload
        def metadata(
            self, value_or_callback: ObjectMeta | None, /
        ) -> "SubjectAccessReview.Builder": ...

        @overload
        def metadata(
            self,
            value_or_callback: Callable[[ObjectMeta.Builder], ObjectMeta.Builder | ObjectMeta],
            /,
        ) -> "SubjectAccessReview.Builder": ...

        @overload
        def metadata(self, value_or_callback: Never = ...) -> "ObjectMeta.BuilderContext": ...

        def metadata(self, value_or_callback=UNSET, /):
            "metadata is the standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata"
            if self._in_context and value_or_callback is UNSET:
                context = ObjectMeta.BuilderContext()
                context._parent_builder = self
                context._field_name = "metadata"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ObjectMeta.builder())
                if isinstance(output, ObjectMeta.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("metadata", value)

        @overload
        def spec(
            self, value_or_callback: SubjectAccessReviewSpec, /
        ) -> "SubjectAccessReview.Builder": ...

        @overload
        def spec(
            self,
            value_or_callback: Callable[
                [SubjectAccessReviewSpec.Builder],
                SubjectAccessReviewSpec.Builder | SubjectAccessReviewSpec,
            ],
            /,
        ) -> "SubjectAccessReview.Builder": ...

        @overload
        def spec(
            self, value_or_callback: Never = ...
        ) -> "SubjectAccessReviewSpec.BuilderContext": ...

        def spec(self, value_or_callback=UNSET, /):
            "spec holds information about the request being evaluated"
            if self._in_context and value_or_callback is UNSET:
                context = SubjectAccessReviewSpec.BuilderContext()
                context._parent_builder = self
                context._field_name = "spec"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(SubjectAccessReviewSpec.builder())
                if isinstance(output, SubjectAccessReviewSpec.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("spec", value)

        @overload
        def status(
            self, value_or_callback: SubjectAccessReviewStatus | None, /
        ) -> "SubjectAccessReview.Builder": ...

        @overload
        def status(
            self,
            value_or_callback: Callable[
                [SubjectAccessReviewStatus.Builder],
                SubjectAccessReviewStatus.Builder | SubjectAccessReviewStatus,
            ],
            /,
        ) -> "SubjectAccessReview.Builder": ...

        @overload
        def status(
            self, value_or_callback: Never = ...
        ) -> "SubjectAccessReviewStatus.BuilderContext": ...

        def status(self, value_or_callback=UNSET, /):
            "status is filled in by the server and indicates whether the request is allowed or not"
            if self._in_context and value_or_callback is UNSET:
                context = SubjectAccessReviewStatus.BuilderContext()
                context._parent_builder = self
                context._field_name = "status"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(SubjectAccessReviewStatus.builder())
                if isinstance(output, SubjectAccessReviewStatus.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("status", value)

    class BuilderContext(BuilderContextBase["SubjectAccessReview.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = SubjectAccessReview.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for SubjectAccessReview."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["SubjectAccessReview", Builder]:
        return GenericListBuilder[SubjectAccessReview, SubjectAccessReview.Builder]()

    api_version: Annotated[Literal["authorization.k8s.io/v1"], Field(alias="apiVersion")] = (
        "authorization.k8s.io/v1"
    )
    "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
    kind: Literal["SubjectAccessReview"] = "SubjectAccessReview"
    "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
    metadata: ObjectMeta | None = None
    "metadata is the standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata"
    spec: SubjectAccessReviewSpec
    "spec holds information about the request being evaluated"
    status: SubjectAccessReviewStatus | None = None
    "status is filled in by the server and indicates whether the request is allowed or not"
