# Generated by cloudcoil-model-codegen v0.7.1
# DO NOT EDIT

from typing import Annotated, Callable, ClassVar, Literal, overload

from cloudcoil.apimachinery import (
    Condition,
    DeleteOptions,
    IntOrString,
    LabelSelector,
    ObjectMeta,
    Time,
)
from cloudcoil.pydantic import (
    UNSET,
    BaseModel,
    BaseModelBuilder,
    BuilderContextBase,
    GenericListBuilder,
    ListBuilderContext,
    Never,
    Self,
)
from cloudcoil.resources import Resource, ResourceList
from pydantic import Field


class Eviction(Resource):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["Eviction"]:
            return Eviction

        def build(self) -> "Eviction":
            return Eviction(**self._attrs)

        def api_version(self, value: Literal["policy/v1"], /) -> Self:
            "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
            return self._set("api_version", value)

        @overload
        def delete_options(
            self, value_or_callback: DeleteOptions | None, /
        ) -> "Eviction.Builder": ...

        @overload
        def delete_options(
            self,
            value_or_callback: Callable[
                [DeleteOptions.Builder], DeleteOptions.Builder | DeleteOptions
            ],
            /,
        ) -> "Eviction.Builder": ...

        @overload
        def delete_options(
            self, value_or_callback: Never = ...
        ) -> "DeleteOptions.BuilderContext": ...

        def delete_options(self, value_or_callback=UNSET, /):
            "DeleteOptions may be provided"
            if self._in_context and value_or_callback is UNSET:
                context = DeleteOptions.BuilderContext()
                context._parent_builder = self
                context._field_name = "delete_options"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(DeleteOptions.builder())
                if isinstance(output, DeleteOptions.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("delete_options", value)

        def kind(self, value: Literal["Eviction"], /) -> Self:
            "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
            return self._set("kind", value)

        @overload
        def metadata(self, value_or_callback: ObjectMeta | None, /) -> "Eviction.Builder": ...

        @overload
        def metadata(
            self,
            value_or_callback: Callable[[ObjectMeta.Builder], ObjectMeta.Builder | ObjectMeta],
            /,
        ) -> "Eviction.Builder": ...

        @overload
        def metadata(self, value_or_callback: Never = ...) -> "ObjectMeta.BuilderContext": ...

        def metadata(self, value_or_callback=UNSET, /):
            "ObjectMeta describes the pod that is being evicted."
            if self._in_context and value_or_callback is UNSET:
                context = ObjectMeta.BuilderContext()
                context._parent_builder = self
                context._field_name = "metadata"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ObjectMeta.builder())
                if isinstance(output, ObjectMeta.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("metadata", value)

    class BuilderContext(BuilderContextBase["Eviction.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = Eviction.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for Eviction."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["Eviction", Builder]:
        return GenericListBuilder[Eviction, Eviction.Builder]()

    api_version: Annotated[Literal["policy/v1"], Field(alias="apiVersion")] = "policy/v1"
    "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
    delete_options: Annotated[DeleteOptions | None, Field(alias="deleteOptions")] = None
    "DeleteOptions may be provided"
    kind: Literal["Eviction"] = "Eviction"
    "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
    metadata: ObjectMeta | None = None
    "ObjectMeta describes the pod that is being evicted."


class PodDisruptionBudgetSpec(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["PodDisruptionBudgetSpec"]:
            return PodDisruptionBudgetSpec

        def build(self) -> "PodDisruptionBudgetSpec":
            return PodDisruptionBudgetSpec(**self._attrs)

        @overload
        def max_unavailable(
            self, value_or_callback: IntOrString | None, /
        ) -> "PodDisruptionBudgetSpec.Builder": ...

        @overload
        def max_unavailable(
            self,
            value_or_callback: Callable[[IntOrString.Builder], IntOrString.Builder | IntOrString],
            /,
        ) -> "PodDisruptionBudgetSpec.Builder": ...

        @overload
        def max_unavailable(
            self, value_or_callback: Never = ...
        ) -> "IntOrString.BuilderContext": ...

        def max_unavailable(self, value_or_callback=UNSET, /):
            'An eviction is allowed if at most "maxUnavailable" pods selected by "selector" are unavailable after the eviction, i.e. even in absence of the evicted pod. For example, one can prevent all voluntary evictions by specifying 0. This is a mutually exclusive setting with "minAvailable".'
            if self._in_context and value_or_callback is UNSET:
                context = IntOrString.BuilderContext()
                context._parent_builder = self
                context._field_name = "max_unavailable"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(IntOrString.builder())
                if isinstance(output, IntOrString.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("max_unavailable", value)

        @overload
        def min_available(
            self, value_or_callback: IntOrString | None, /
        ) -> "PodDisruptionBudgetSpec.Builder": ...

        @overload
        def min_available(
            self,
            value_or_callback: Callable[[IntOrString.Builder], IntOrString.Builder | IntOrString],
            /,
        ) -> "PodDisruptionBudgetSpec.Builder": ...

        @overload
        def min_available(self, value_or_callback: Never = ...) -> "IntOrString.BuilderContext": ...

        def min_available(self, value_or_callback=UNSET, /):
            'An eviction is allowed if at least "minAvailable" pods selected by "selector" will still be available after the eviction, i.e. even in the absence of the evicted pod.  So for example you can prevent all voluntary evictions by specifying "100%".'
            if self._in_context and value_or_callback is UNSET:
                context = IntOrString.BuilderContext()
                context._parent_builder = self
                context._field_name = "min_available"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(IntOrString.builder())
                if isinstance(output, IntOrString.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("min_available", value)

        @overload
        def selector(
            self, value_or_callback: LabelSelector | None, /
        ) -> "PodDisruptionBudgetSpec.Builder": ...

        @overload
        def selector(
            self,
            value_or_callback: Callable[
                [LabelSelector.Builder], LabelSelector.Builder | LabelSelector
            ],
            /,
        ) -> "PodDisruptionBudgetSpec.Builder": ...

        @overload
        def selector(self, value_or_callback: Never = ...) -> "LabelSelector.BuilderContext": ...

        def selector(self, value_or_callback=UNSET, /):
            "Label query over pods whose evictions are managed by the disruption budget. A null selector will match no pods, while an empty ({}) selector will select all pods within the namespace."
            if self._in_context and value_or_callback is UNSET:
                context = LabelSelector.BuilderContext()
                context._parent_builder = self
                context._field_name = "selector"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(LabelSelector.builder())
                if isinstance(output, LabelSelector.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("selector", value)

        def unhealthy_pod_eviction_policy(self, value: str | None, /) -> Self:
            'UnhealthyPodEvictionPolicy defines the criteria for when unhealthy pods should be considered for eviction. Current implementation considers healthy pods, as pods that have status.conditions item with type="Ready",status="True".\n\nValid policies are IfHealthyBudget and AlwaysAllow. If no policy is specified, the default behavior will be used, which corresponds to the IfHealthyBudget policy.\n\nIfHealthyBudget policy means that running pods (status.phase="Running"), but not yet healthy can be evicted only if the guarded application is not disrupted (status.currentHealthy is at least equal to status.desiredHealthy). Healthy pods will be subject to the PDB for eviction.\n\nAlwaysAllow policy means that all running pods (status.phase="Running"), but not yet healthy are considered disrupted and can be evicted regardless of whether the criteria in a PDB is met. This means perspective running pods of a disrupted application might not get a chance to become healthy. Healthy pods will be subject to the PDB for eviction.\n\nAdditional policies may be added in the future. Clients making eviction decisions should disallow eviction of unhealthy pods if they encounter an unrecognized policy in this field.'
            return self._set("unhealthy_pod_eviction_policy", value)

    class BuilderContext(BuilderContextBase["PodDisruptionBudgetSpec.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = PodDisruptionBudgetSpec.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for PodDisruptionBudgetSpec."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["PodDisruptionBudgetSpec", Builder]:
        return GenericListBuilder[PodDisruptionBudgetSpec, PodDisruptionBudgetSpec.Builder]()

    max_unavailable: Annotated[IntOrString | None, Field(alias="maxUnavailable")] = None
    'An eviction is allowed if at most "maxUnavailable" pods selected by "selector" are unavailable after the eviction, i.e. even in absence of the evicted pod. For example, one can prevent all voluntary evictions by specifying 0. This is a mutually exclusive setting with "minAvailable".'
    min_available: Annotated[IntOrString | None, Field(alias="minAvailable")] = None
    'An eviction is allowed if at least "minAvailable" pods selected by "selector" will still be available after the eviction, i.e. even in the absence of the evicted pod.  So for example you can prevent all voluntary evictions by specifying "100%".'
    selector: LabelSelector | None = None
    "Label query over pods whose evictions are managed by the disruption budget. A null selector will match no pods, while an empty ({}) selector will select all pods within the namespace."
    unhealthy_pod_eviction_policy: Annotated[
        str | None, Field(alias="unhealthyPodEvictionPolicy")
    ] = None
    'UnhealthyPodEvictionPolicy defines the criteria for when unhealthy pods should be considered for eviction. Current implementation considers healthy pods, as pods that have status.conditions item with type="Ready",status="True".\n\nValid policies are IfHealthyBudget and AlwaysAllow. If no policy is specified, the default behavior will be used, which corresponds to the IfHealthyBudget policy.\n\nIfHealthyBudget policy means that running pods (status.phase="Running"), but not yet healthy can be evicted only if the guarded application is not disrupted (status.currentHealthy is at least equal to status.desiredHealthy). Healthy pods will be subject to the PDB for eviction.\n\nAlwaysAllow policy means that all running pods (status.phase="Running"), but not yet healthy are considered disrupted and can be evicted regardless of whether the criteria in a PDB is met. This means perspective running pods of a disrupted application might not get a chance to become healthy. Healthy pods will be subject to the PDB for eviction.\n\nAdditional policies may be added in the future. Clients making eviction decisions should disallow eviction of unhealthy pods if they encounter an unrecognized policy in this field.'


class PodDisruptionBudgetStatus(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["PodDisruptionBudgetStatus"]:
            return PodDisruptionBudgetStatus

        def build(self) -> "PodDisruptionBudgetStatus":
            return PodDisruptionBudgetStatus(**self._attrs)

        @overload
        def conditions(
            self, value_or_callback: list[Condition] | None, /
        ) -> "PodDisruptionBudgetStatus.Builder": ...

        @overload
        def conditions(
            self,
            value_or_callback: Callable[
                [GenericListBuilder[Condition, Condition.Builder]],
                GenericListBuilder[Condition, Condition.Builder] | list[Condition],
            ],
            /,
        ) -> "PodDisruptionBudgetStatus.Builder": ...

        @overload
        def conditions(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[Condition.Builder]: ...

        def conditions(self, value_or_callback=UNSET, /):
            "Conditions contain conditions for PDB. The disruption controller sets the DisruptionAllowed condition. The following are known values for the reason field (additional reasons could be added in the future): - SyncFailed: The controller encountered an error and wasn\u0027t able to compute\n              the number of allowed disruptions. Therefore no disruptions are\n              allowed and the status of the condition will be False.\n- InsufficientPods: The number of pods are either at or below the number\n                    required by the PodDisruptionBudget. No disruptions are\n                    allowed and the status of the condition will be False.\n- SufficientPods: There are more pods than required by the PodDisruptionBudget.\n                  The condition will be True, and the number of allowed\n                  disruptions are provided by the disruptionsAllowed property."
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[Condition.Builder]()
                context._parent_builder = self
                context._field_name = "conditions"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(Condition.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("conditions", value)

        def current_healthy(self, value: int, /) -> Self:
            "current number of healthy pods"
            return self._set("current_healthy", value)

        def desired_healthy(self, value: int, /) -> Self:
            "minimum desired number of healthy pods"
            return self._set("desired_healthy", value)

        def disrupted_pods(self, value: dict[str, Time] | None, /) -> Self:
            "DisruptedPods contains information about pods whose eviction was processed by the API server eviction subresource handler but has not yet been observed by the PodDisruptionBudget controller. A pod will be in this map from the time when the API server processed the eviction request to the time when the pod is seen by PDB controller as having been marked for deletion (or after a timeout). The key in the map is the name of the pod and the value is the time when the API server processed the eviction request. If the deletion didn\u0027t occur and a pod is still there it will be removed from the list automatically by PodDisruptionBudget controller after some time. If everything goes smooth this map should be empty for the most of the time. Large number of entries in the map may indicate problems with pod deletions."
            return self._set("disrupted_pods", value)

        def disruptions_allowed(self, value: int, /) -> Self:
            "Number of pod disruptions that are currently allowed."
            return self._set("disruptions_allowed", value)

        def expected_pods(self, value: int, /) -> Self:
            "total number of pods counted by this disruption budget"
            return self._set("expected_pods", value)

        def observed_generation(self, value: int | None, /) -> Self:
            "Most recent generation observed when updating this PDB status. DisruptionsAllowed and other status information is valid only if observedGeneration equals to PDB\u0027s object generation."
            return self._set("observed_generation", value)

    class BuilderContext(BuilderContextBase["PodDisruptionBudgetStatus.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = PodDisruptionBudgetStatus.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for PodDisruptionBudgetStatus."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["PodDisruptionBudgetStatus", Builder]:
        return GenericListBuilder[PodDisruptionBudgetStatus, PodDisruptionBudgetStatus.Builder]()

    conditions: list[Condition] | None = None
    "Conditions contain conditions for PDB. The disruption controller sets the DisruptionAllowed condition. The following are known values for the reason field (additional reasons could be added in the future): - SyncFailed: The controller encountered an error and wasn\u0027t able to compute\n              the number of allowed disruptions. Therefore no disruptions are\n              allowed and the status of the condition will be False.\n- InsufficientPods: The number of pods are either at or below the number\n                    required by the PodDisruptionBudget. No disruptions are\n                    allowed and the status of the condition will be False.\n- SufficientPods: There are more pods than required by the PodDisruptionBudget.\n                  The condition will be True, and the number of allowed\n                  disruptions are provided by the disruptionsAllowed property."
    current_healthy: Annotated[int, Field(alias="currentHealthy")]
    "current number of healthy pods"
    desired_healthy: Annotated[int, Field(alias="desiredHealthy")]
    "minimum desired number of healthy pods"
    disrupted_pods: Annotated[dict[str, Time] | None, Field(alias="disruptedPods")] = None
    "DisruptedPods contains information about pods whose eviction was processed by the API server eviction subresource handler but has not yet been observed by the PodDisruptionBudget controller. A pod will be in this map from the time when the API server processed the eviction request to the time when the pod is seen by PDB controller as having been marked for deletion (or after a timeout). The key in the map is the name of the pod and the value is the time when the API server processed the eviction request. If the deletion didn\u0027t occur and a pod is still there it will be removed from the list automatically by PodDisruptionBudget controller after some time. If everything goes smooth this map should be empty for the most of the time. Large number of entries in the map may indicate problems with pod deletions."
    disruptions_allowed: Annotated[int, Field(alias="disruptionsAllowed")]
    "Number of pod disruptions that are currently allowed."
    expected_pods: Annotated[int, Field(alias="expectedPods")]
    "total number of pods counted by this disruption budget"
    observed_generation: Annotated[int | None, Field(alias="observedGeneration")] = None
    "Most recent generation observed when updating this PDB status. DisruptionsAllowed and other status information is valid only if observedGeneration equals to PDB\u0027s object generation."


class PodDisruptionBudget(Resource):
    __cloudcoil_api__: ClassVar[dict] = {
        "plural": "poddisruptionbudgets",
        "scope": "Namespaced",
        "status": False,
    }

    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["PodDisruptionBudget"]:
            return PodDisruptionBudget

        def build(self) -> "PodDisruptionBudget":
            return PodDisruptionBudget(**self._attrs)

        def api_version(self, value: Literal["policy/v1"], /) -> Self:
            "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
            return self._set("api_version", value)

        def kind(self, value: Literal["PodDisruptionBudget"], /) -> Self:
            "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
            return self._set("kind", value)

        @overload
        def metadata(
            self, value_or_callback: ObjectMeta | None, /
        ) -> "PodDisruptionBudget.Builder": ...

        @overload
        def metadata(
            self,
            value_or_callback: Callable[[ObjectMeta.Builder], ObjectMeta.Builder | ObjectMeta],
            /,
        ) -> "PodDisruptionBudget.Builder": ...

        @overload
        def metadata(self, value_or_callback: Never = ...) -> "ObjectMeta.BuilderContext": ...

        def metadata(self, value_or_callback=UNSET, /):
            "Standard object\u0027s metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata"
            if self._in_context and value_or_callback is UNSET:
                context = ObjectMeta.BuilderContext()
                context._parent_builder = self
                context._field_name = "metadata"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ObjectMeta.builder())
                if isinstance(output, ObjectMeta.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("metadata", value)

        @overload
        def spec(
            self, value_or_callback: PodDisruptionBudgetSpec | None, /
        ) -> "PodDisruptionBudget.Builder": ...

        @overload
        def spec(
            self,
            value_or_callback: Callable[
                [PodDisruptionBudgetSpec.Builder],
                PodDisruptionBudgetSpec.Builder | PodDisruptionBudgetSpec,
            ],
            /,
        ) -> "PodDisruptionBudget.Builder": ...

        @overload
        def spec(
            self, value_or_callback: Never = ...
        ) -> "PodDisruptionBudgetSpec.BuilderContext": ...

        def spec(self, value_or_callback=UNSET, /):
            "Specification of the desired behavior of the PodDisruptionBudget."
            if self._in_context and value_or_callback is UNSET:
                context = PodDisruptionBudgetSpec.BuilderContext()
                context._parent_builder = self
                context._field_name = "spec"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(PodDisruptionBudgetSpec.builder())
                if isinstance(output, PodDisruptionBudgetSpec.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("spec", value)

        @overload
        def status(
            self, value_or_callback: PodDisruptionBudgetStatus | None, /
        ) -> "PodDisruptionBudget.Builder": ...

        @overload
        def status(
            self,
            value_or_callback: Callable[
                [PodDisruptionBudgetStatus.Builder],
                PodDisruptionBudgetStatus.Builder | PodDisruptionBudgetStatus,
            ],
            /,
        ) -> "PodDisruptionBudget.Builder": ...

        @overload
        def status(
            self, value_or_callback: Never = ...
        ) -> "PodDisruptionBudgetStatus.BuilderContext": ...

        def status(self, value_or_callback=UNSET, /):
            "Most recently observed status of the PodDisruptionBudget."
            if self._in_context and value_or_callback is UNSET:
                context = PodDisruptionBudgetStatus.BuilderContext()
                context._parent_builder = self
                context._field_name = "status"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(PodDisruptionBudgetStatus.builder())
                if isinstance(output, PodDisruptionBudgetStatus.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("status", value)

    class BuilderContext(BuilderContextBase["PodDisruptionBudget.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = PodDisruptionBudget.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for PodDisruptionBudget."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["PodDisruptionBudget", Builder]:
        return GenericListBuilder[PodDisruptionBudget, PodDisruptionBudget.Builder]()

    api_version: Annotated[Literal["policy/v1"], Field(alias="apiVersion")] = "policy/v1"
    "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
    kind: Literal["PodDisruptionBudget"] = "PodDisruptionBudget"
    "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
    metadata: ObjectMeta | None = None
    "Standard object\u0027s metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata"
    spec: PodDisruptionBudgetSpec | None = None
    "Specification of the desired behavior of the PodDisruptionBudget."
    status: PodDisruptionBudgetStatus | None = None
    "Most recently observed status of the PodDisruptionBudget."


PodDisruptionBudgetList = ResourceList[PodDisruptionBudget]
