# Generated by cloudcoil-model-codegen v0.7.0
# DO NOT EDIT

from typing import Annotated, Callable, ClassVar, Literal, overload

from cloudcoil.apimachinery import (
    MicroTime,
    ObjectMeta,
)
from cloudcoil.pydantic import (
    UNSET,
    BaseModel,
    BaseModelBuilder,
    BuilderContextBase,
    GenericListBuilder,
    Never,
    Self,
)
from cloudcoil.resources import Resource, ResourceList
from pydantic import Field


class LeaseSpec(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["LeaseSpec"]:
            return LeaseSpec

        def build(self) -> "LeaseSpec":
            return LeaseSpec(**self._attrs)

        @overload
        def acquire_time(self, value_or_callback: MicroTime | None, /) -> "LeaseSpec.Builder": ...

        @overload
        def acquire_time(
            self,
            value_or_callback: Callable[[MicroTime.Builder], MicroTime.Builder | MicroTime],
            /,
        ) -> "LeaseSpec.Builder": ...

        @overload
        def acquire_time(self, value_or_callback: Never = ...) -> "MicroTime.BuilderContext": ...

        def acquire_time(self, value_or_callback=UNSET, /):
            "acquireTime is a time when the current lease was acquired."
            if self._in_context and value_or_callback is UNSET:
                context = MicroTime.BuilderContext()
                context._parent_builder = self
                context._field_name = "acquire_time"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(MicroTime.builder())
                if isinstance(output, MicroTime.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("acquire_time", value)

        def holder_identity(self, value: str | None, /) -> Self:
            "holderIdentity contains the identity of the holder of a current lease. If Coordinated Leader Election is used, the holder identity must be equal to the elected LeaseCandidate.metadata.name field."
            return self._set("holder_identity", value)

        def lease_duration_seconds(self, value: int | None, /) -> Self:
            "leaseDurationSeconds is a duration that candidates for a lease need to wait to force acquire it. This is measured against the time of last observed renewTime."
            return self._set("lease_duration_seconds", value)

        def lease_transitions(self, value: int | None, /) -> Self:
            "leaseTransitions is the number of transitions of a lease between holders."
            return self._set("lease_transitions", value)

        def preferred_holder(self, value: str | None, /) -> Self:
            "PreferredHolder signals to a lease holder that the lease has a more optimal holder and should be given up. This field can only be set if Strategy is also set."
            return self._set("preferred_holder", value)

        @overload
        def renew_time(self, value_or_callback: MicroTime | None, /) -> "LeaseSpec.Builder": ...

        @overload
        def renew_time(
            self,
            value_or_callback: Callable[[MicroTime.Builder], MicroTime.Builder | MicroTime],
            /,
        ) -> "LeaseSpec.Builder": ...

        @overload
        def renew_time(self, value_or_callback: Never = ...) -> "MicroTime.BuilderContext": ...

        def renew_time(self, value_or_callback=UNSET, /):
            "renewTime is a time when the current holder of a lease has last updated the lease."
            if self._in_context and value_or_callback is UNSET:
                context = MicroTime.BuilderContext()
                context._parent_builder = self
                context._field_name = "renew_time"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(MicroTime.builder())
                if isinstance(output, MicroTime.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("renew_time", value)

        def strategy(self, value: str | None, /) -> Self:
            "Strategy indicates the strategy for picking the leader for coordinated leader election. If the field is not specified, there is no active coordination for this lease. (Alpha) Using this field requires the CoordinatedLeaderElection feature gate to be enabled."
            return self._set("strategy", value)

    class BuilderContext(BuilderContextBase["LeaseSpec.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = LeaseSpec.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for LeaseSpec."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["LeaseSpec", Builder]:
        return GenericListBuilder[LeaseSpec, LeaseSpec.Builder]()

    acquire_time: Annotated[MicroTime | None, Field(alias="acquireTime")] = None
    "acquireTime is a time when the current lease was acquired."
    holder_identity: Annotated[str | None, Field(alias="holderIdentity")] = None
    "holderIdentity contains the identity of the holder of a current lease. If Coordinated Leader Election is used, the holder identity must be equal to the elected LeaseCandidate.metadata.name field."
    lease_duration_seconds: Annotated[int | None, Field(alias="leaseDurationSeconds")] = None
    "leaseDurationSeconds is a duration that candidates for a lease need to wait to force acquire it. This is measured against the time of last observed renewTime."
    lease_transitions: Annotated[int | None, Field(alias="leaseTransitions")] = None
    "leaseTransitions is the number of transitions of a lease between holders."
    preferred_holder: Annotated[str | None, Field(alias="preferredHolder")] = None
    "PreferredHolder signals to a lease holder that the lease has a more optimal holder and should be given up. This field can only be set if Strategy is also set."
    renew_time: Annotated[MicroTime | None, Field(alias="renewTime")] = None
    "renewTime is a time when the current holder of a lease has last updated the lease."
    strategy: str | None = None
    "Strategy indicates the strategy for picking the leader for coordinated leader election. If the field is not specified, there is no active coordination for this lease. (Alpha) Using this field requires the CoordinatedLeaderElection feature gate to be enabled."


class Lease(Resource):
    __cloudcoil_api__: ClassVar[dict] = {
        "plural": "leases",
        "scope": "Namespaced",
        "status": False,
    }

    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["Lease"]:
            return Lease

        def build(self) -> "Lease":
            return Lease(**self._attrs)

        def api_version(self, value: Literal["coordination.k8s.io/v1"], /) -> Self:
            "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
            return self._set("api_version", value)

        def kind(self, value: Literal["Lease"], /) -> Self:
            "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
            return self._set("kind", value)

        @overload
        def metadata(self, value_or_callback: ObjectMeta | None, /) -> "Lease.Builder": ...

        @overload
        def metadata(
            self,
            value_or_callback: Callable[[ObjectMeta.Builder], ObjectMeta.Builder | ObjectMeta],
            /,
        ) -> "Lease.Builder": ...

        @overload
        def metadata(self, value_or_callback: Never = ...) -> "ObjectMeta.BuilderContext": ...

        def metadata(self, value_or_callback=UNSET, /):
            "More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata"
            if self._in_context and value_or_callback is UNSET:
                context = ObjectMeta.BuilderContext()
                context._parent_builder = self
                context._field_name = "metadata"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ObjectMeta.builder())
                if isinstance(output, ObjectMeta.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("metadata", value)

        @overload
        def spec(self, value_or_callback: LeaseSpec | None, /) -> "Lease.Builder": ...

        @overload
        def spec(
            self,
            value_or_callback: Callable[[LeaseSpec.Builder], LeaseSpec.Builder | LeaseSpec],
            /,
        ) -> "Lease.Builder": ...

        @overload
        def spec(self, value_or_callback: Never = ...) -> "LeaseSpec.BuilderContext": ...

        def spec(self, value_or_callback=UNSET, /):
            "spec contains the specification of the Lease. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status"
            if self._in_context and value_or_callback is UNSET:
                context = LeaseSpec.BuilderContext()
                context._parent_builder = self
                context._field_name = "spec"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(LeaseSpec.builder())
                if isinstance(output, LeaseSpec.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("spec", value)

    class BuilderContext(BuilderContextBase["Lease.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = Lease.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for Lease."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["Lease", Builder]:
        return GenericListBuilder[Lease, Lease.Builder]()

    api_version: Annotated[Literal["coordination.k8s.io/v1"], Field(alias="apiVersion")] = (
        "coordination.k8s.io/v1"
    )
    "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
    kind: Literal["Lease"] = "Lease"
    "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
    metadata: ObjectMeta | None = None
    "More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata"
    spec: LeaseSpec | None = None
    "spec contains the specification of the Lease. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status"


LeaseList = ResourceList[Lease]
