
name: Update Versions

on:
  push:
    branches:
      - main
jobs:
  update-versions:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        model_version: ['1.29.13', '1.30.9', '1.31.5', '1.32.1']

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.CI_GITHUB_TOKEN }}
      - name: Install uv and set python
        uses: astral-sh/setup-uv@v4
        with:
          python-version: '3.10'
          enable-cache: true
          cache-dependency-glob: "**/uv.lock"

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Update version for ${{ matrix.model_version }}
        run: |
          uv add cloudcoil -U
          VERSION="${{ matrix.model_version }}.0"
          MINOR_VERSION=$(echo "${{ matrix.model_version }}" | cut -d'.' -f1,2)
          BRANCH="release-${MINOR_VERSION}"
          # Update version and input URL using sed
          sed -i "s/^version = .*/version = \"${VERSION}\"/" pyproject.toml
          sed -i "s|refs/tags/v[0-9]\+\.[0-9]\+\.[0-9]\+/|refs/tags/v${{ matrix.model_version }}/|" pyproject.toml
          # Generate models
          make gen-models
          # Configure git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Create temporary directory and handle repository
          TEMP_DIR=$(mktemp -d)
          cd "$TEMP_DIR"

          # Clone repo and checkout/create branch
          git clone https://github.com/${{ github.repository }}.git .
          git checkout "$BRANCH" 2>/dev/null || git checkout -b "$BRANCH"

          # Clear existing files (except .git)
          find . -mindepth 1 -not -path './.git*' -delete

          # Copy new files and commit
          cp -a $GITHUB_WORKSPACE/. .
          git add -A
          git diff --cached --quiet || git commit -m "Update to version ${{ matrix.model_version }}"
          git push -u origin HEAD:"$BRANCH"